GoogleCloudPlatform/ml-auto-solutions

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/require-checklist.yaml

Add pull request template, this is a similar PR with [#814](https://github.com/GoogleCloudPlatform/ml-testing-accelerators/pull/814).
**Instruction and/or command lines to reproduce your tests:** N/A
**List links for your tests (use go/shortn-gen for any internal link):** N/A

Add pull request template

---

dags/xlml/solutionsTeam_flax_latest_supported.py
implementations/utils/tpu.py

Update the key name from `xl-ml-test` to `ml-auto-solutions` to be consistent with the project. Also, update the V3 test dependency as the fix has been merged and wait for roll out (b/305310198). 
Upload to Airflow to have a run.
* Dependency graph: [link](https://screenshot.googleplex.com/AXtThRpe8dY472C)
* A run to SSH: [link](https://screenshot.googleplex.com/BJeuVATE5EUQ6vu)

Update the key name and model dependency

---

apis/task.py
apis/test_config.py
configs/xlml/tensorflow/solutionsTeam_tf_nightly_supported_config.py

Move common attributes from TpuVmTest to TestConfig to address missing attributes issue in [JsonnetTpuVmTest](https://screenshot.googleplex.com/BqJCQ4tf7sgA7Kv)
Upload the Airflow code, and no error is there. Then, trigger a test that is converted from Jsonnet.
Test run: [link](https://screenshot.googleplex.com/3wrcBh75atvQiha)

Move common attributes from TpuVmTest to TestConfig

---

apis/metric_config.py
configs/composer_env.py
dags/xlml/solutionsTeam_flax_latest_supported.py
dags/xlml/solutionsTeam_tf_nightly_supported.py
deployment/cloud_composer.auto.tfvars
deployment/cloud_composer_template.tf
implementations/utils/metric.py
implementations/utils/metric_test.py

Add dev composer environment.
* Add dev env entry into Terraform.
* Add a helper function to check if entries are valid to BigQuery table.
* Add unit tests accordingly.
I think we still need to think about how we cooperate with various projects/datasets, i.e. should different team creates a separate Composer environment (gcs sync-up with the repo) or use the same one? For now, only prod and scheduled tests entries will be inserted to the table.
* Unit tests
* Airflow run
* Unit tests for metric_test.py: [link](https://paste.googleplex.com/6281126409666560)
* Created Airflow: …

Add dev composer environment

---

configs/xlml/jax/solutionsTeam_flax_latest_supported_config.py
dags/benchmark/solutionsTeam_jax_npi.py
dags/xlml/solutionsTeam_flax_latest_supported.py
dags/xlml/solutionsTeam_jax_latest_integration.py
dags/xlml/solutionsTeam_tf_nightly_supported.py

Organize and update JAX tests:
* Updated file name, dag ID, and labels to be consistent in JAX
* Scheduled the JAX integration test, updated the TPU zone, and removed deleted test accordingly ([pr](https://github.com/GoogleCloudPlatform/ml-testing-accelerators/pull/1005)).
* Other small changes, such as type, dependency fix
Upload to airflow and test it.
* UI overview: [link](https://screenshot.googleplex.com/799XAipV72gfwW6)
* JAX integration tests: [link](https://screenshot.googleplex.com/7fRjkaeXuKGkCZy)
* Flax model tests: …

Organize and update JAX tests

---

configs/xlml/jax/solutionsTeam_flax_latest_supported_config.py
dags/xlml/solutionsTeam_flax_latest_supported.py

Add JAX/FLAX ViT model for v4-8 and v4-32.
Upload to Airflow to run test.
* Test [link](https://screenshot.googleplex.com/3kVeeLo7LbPgNM8)

Add JAX/FLAX ViT model

---

configs/gcs_bucket.py
configs/vm_resource.py
configs/xlml/jax/common.py
configs/xlml/jax/solutionsTeam_pax_latest_supported_config.py
dags/xlml/solutionsTeam_pax_latest_supported.py

Add three PAX stable model [tests](https://screenshot.googleplex.com/8zxidSEsj5z6P2N). To be consistent with existing Airflow test format:
* Update the test name a little bit by adding dataset name
* Update the test name "stable" to "latest" to indicate the version at this moment (please let me know if you have any concerns)
* Will need to adjust the schedule info in a separate PR once quota is finalized
Upload to Airflow to run tests.
Test [link](https://screenshot.googleplex.com/87ytWDbQEGH9Bex)

Add PAX stable model tests

---

configs/xlml/jax/solutionsTeam_flax_latest_supported_config.py
dags/xlml/solutionsTeam_flax_latest_supported.py
dags/xlml/solutionsTeam_jax_latest_integration.py
dags/xlml/solutionsTeam_tf_nightly_supported.py

* Add more JAX model tests: BART, BERT, WMT (with v4 for now)
* Add `generate_unique_dir` method to ensure retry start from scratch if there is no overwrite flag available.
* Not able to get WMT working on v4-32 (stuck for a couple of hours without any error, & also not exists in current xl ml repo), so WMT is tested on v4-8 for now
* Add PST time zone for schedule (schedule will need to be updated based on the final quota)
Upload to Airflow and run tests.
Test [link](https://screenshot.googleplex.com/9kqw2vHjeBDsyaa)
Before submitting this PR, please make sure (put X in square …

Add more JAX model tests 

---

configs/vm_resource.py
configs/xlml/tensorflow/solutionsTeam_tf_nightly_supported_config.py

Currently, it is not able to provision the TPUs to run TensorFlow tests with old nightly images, so update image name.
Test: [link](https://screenshot.googleplex.com/38qwtxXDHmenNZu) - able to provision the resource

Update nightly image name

---

dags/xlml/pytorchxla_huggingface.py
dags/xlml/pytorchxla_llama.py
dags/xlml/pytorchxla_torchvision.py
dags/xlml/solutionsTeam_pax_latest_supported.py

Add schedule for PyTorch XLML tests.
Not easy to test until it's prod env (schedule will be removed in other env).
N/A

Schedule periodic run for PT tests

---

configs/benchmark/pytorch/pytorchxla_torchbench_config.py

Update the config/run script for BERT_pytorch.
Here is the test for BERT_pytorch [link](https://08398f98ca104983a06a424b851a390d-dot-us-central1.composer.googleusercontent.com/dags/pytorch_nightly_torchbench/grid?dag_run_id=manual__2023-11-16T05%3A46%3A27.554037%2B00%3A00&task_id=torchbench_BERT_pytorch-v4-8.clean_up&tab=graph).

update torchbench running script

---

configs/benchmark/pytorch/pytorchxla_torchbench_config.py
configs/test_owner.py
dags/benchmark/pytorchxla_torchbench.py

Add 4 extra torchbench models. Some models are intentioned to fail.
[Dag runs](https://08398f98ca104983a06a424b851a390d-dot-us-central1.composer.googleusercontent.com/dags/pytorch_nightly_torchbench/grid?dag_run_id=manual__2023-11-21T17%3A22%3A58.775215%2B00%3A00&tab=graph&task_id=torchbench_Super_SloMo-v4-8).

Add four extra torchbench models

---

.github/workflows/unit-test.yml

Update the job name for unit test check.

Update workflow name to unit test

---

pipeline/auto-push.cloudbuild.yml

Add auto push feature after the merge via cloudbuild
Set up cloudbuild in the project, and manually trigger the build
Build [link](http://shortn/_kQC4V2b9bM)

Add auto push after commit merge

---

README.md

Update email address in README file, and also other small changes.
**Instruction and/or command lines to reproduce your tests:** ... N/A
**List links for your tests (use go/shortn-gen for any internal link):** ...N/A

Update email address in README file

---

implementations/utils/metric.py

Fix conditional statement for attribute.
* Error message: `AttributeError: 'TpuVmTest' object has no attribute 'cluster_name'`
Test [link](https://screenshot.googleplex.com/fSDmqKXztNc2pCW)

Fix conditional statement for attribute

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
apis/task.py
configs/vm_resource.py
configs/xlml/jax/solutionsteam_flax_latest_supported_config.py
configs/xlml/pax/solutionsteam_pax_supported_config.py
configs/xlml/tensorflow/solutionsteam_tf_nightly_supported_config.py
dags/xlml/pytorchxla_huggingface.py
dags/xlml/pytorchxla_torchvision.py
dags/xlml/solutionsteam_jax_integration.py
implementations/utils/bigquery.py
implementations/utils/bigquery_test.py
implementations/utils/metric.py
implementations/utils/metric_test.py
implementations/utils/ssh.py
implementations/utils/tpu.py
implementations/utils/xpk.py
scripts/format-codes.sh

Change-Id: Id41bf91cda3ec7a53ea755c6a15237f126f5f0f7
Add format checking:
* Add GitHub check and pre-commit config for formatter
* When adding a formatter, I was considering: 1) popularity; 2) easy of usage; 3) active maintenance; and 4) internal workspace compatibility - as we will develop an automated workflow in G3 for NPI
* [Pyink](https://github.com/google/pyink/tree/pyink) is a better option, compared to Black and YAPF.
* Pyink is a fork of black that providing a few different behaviors towards to google3
* YAPF is transitioning to Pyink internally
* Pyink has pre-commit integration (although no GitHub action is available yet)
* Open source version of [Pyformat](https://g3doc.corp.google.com/devtools/python/pyformat/g3doc/index.md?cl=head) with small delta 
I just realized we could …

Add format checking

---

docs/contributing.md

Change-Id: I1e3acdb401691ce8097f890d33c63f0e384eb3db
Add instruction to format codes.
Manually verified.

Add instruction to format codes

---

configs/vm_resource.py
configs/xlml/tensorflow/common.py
configs/xlml/tensorflow/solutionsteam_tf_nightly_supported_config.py
dags/xlml/solutionsteam_tf_nightly_supported.py

Update TensorFlow ResNet tests to PJRT nightly:
* Follow old tests that use a base image + [pull nightly tf whl](https://github.com/GoogleCloudPlatform/ml-testing-accelerators/blob/91a9bb1361ace213c5e722adabf36f2b2f8581c5/tests/tensorflow/nightly/common.libsonnet#L179-L188) + proper [flags](https://github.com/GoogleCloudPlatform/ml-testing-accelerators/blob/91a9bb1361ace213c5e722adabf36f2b2f8581c5/tests/tensorflow/nightly/common.libsonnet#L115-L123)
* Add v5e and v5p single host tests (will add multi-host later)
* Other small changes
Test: …

Update TensorFlow ResNet tests

---

apis/gcp_config.py
apis/test_config.py
configs/benchmark/pytorch/pytorchxla_torchbench_config.py
configs/example/xpk_example_config.py
configs/vm_resource.py
configs/xlml/jax/solutionsteam_flax_latest_supported_config.py
configs/xlml/pax/solutionsteam_pax_supported_config.py
configs/xlml/tensorflow/solutionsteam_tf_nightly_supported_config.py
dags/benchmark/pytorchxla_torchbench.py
dags/example/xpk_example_dag.py
dags/xlml/pytorchxla_huggingface.py
dags/xlml/pytorchxla_llama.py
dags/xlml/pytorchxla_torchvision.py
dags/xlml/solutionsteam_flax_latest_supported.py
dags/xlml/solutionsteam_jax_integration.py
dags/xlml/solutionsteam_pax_latest_supported.py
dags/xlml/solutionsteam_pax_nightly_supported.py
dags/xlml/solutionsteam_tf_nightly_supported.py

* Update TPU version from String to Enum 
* Other small changes: 1) remove unused import; 2) remove completed TODOs; 3) update default project name in pax to the right one.
* TF nightly: [test](https://screenshot.googleplex.com/9DAKzSL2DijMUqa)
* Jax latest: [test](https://screenshot.googleplex.com/4JHVFsgJuejgk9o)
* TorchBench: [test](https://screenshot.googleplex.com/C7PK4uiY4FBBSmv)
* Pax: [test](https://screenshot.googleplex.com/38Q6J4HVoUU5YXf) - unfortunately, all PAX tests failed due to dependency issue
Before submitting this PR, please make …

Update TPU version from String to Enum

---

dags/xlml/solutionsteam_pax_nightly_supported.py

This PR adds additional tests for pax nightly
- `pax_nightly_c4spmd1b_pretraining-v4-8`:  http://shortn/_FCn5KjYKRh
- `pax_nightly_lmcloudspmdadam-v4-16`: http://shortn/_6h9vHNZFMU
- `pax_nightly_lmtransformer-v5p-4`: http://shortn/_bseEel8LW7
- `pax_nightly_lmtransformer-v5p-16`:
- http://shortn/_VbU2beBZTI
Unfortunately, these tests aren't passing since all pax nightly tests aren't passing.

added remaining nightly pax tests

---

configs/xlml/jax/solutionsteam_flax_latest_supported_config.py
dags/xlml/solutionsteam_flax_latest_supported.py

Add Flax v5e tests:
* Add existing v5e tests to Airflow: ViT, GPT2, SD
* Update helper configs to include project_name and network info as v5e capacity is in different project
* Other small changes, i.e. rename variables
Upload to airflow and test
Test: [link](https://screenshot.googleplex.com/8zAhfknW8JfUVf7)

Add flax v5e tests

---

configs/xlml/tensorflow/solutionsteam_tf_nightly_supported_config.py
dags/xlml/solutionsteam_tf_nightly_supported.py

Add pod tests for TF PJRT ResNet:
* Add ResNet on v4-32, v5litepod-16, and v5p-32
* Update Keras helper config to enable pod tests (I did not add it now, as current Keras are running on single host only)
ResNet pod test: [link](https://screenshot.googleplex.com/oBwgcY2Ya7Lwy48)

Add pod tests for TF PJRT ResNet

---

configs/xlml/pax/solutionsteam_pax_supported_config.py

For the nightly pax tests, the pip version needs to be upgraded.
NA

add pip upgrade for pax tests

---

configs/xlml/jax/solutionsteam_flax_latest_supported_config.py
dags/xlml/solutionsteam_flax_latest_supported.py

Based on [quota](https://screenshot.googleplex.com/53eWakTegGsznXc), update Flax v4-32 tests to use on-demand resources.
Expect checks all pass.

Update Flax v4-32 tests to use on-demand resources

---

dags/gcs_bucket.py

Datasets have been migrated to `gs://ml-auto-solutions/data` bucket, so update the path in source codes accordingly.
* Source of datasets: [link](https://github.com/GoogleCloudPlatform/ml-testing-accelerators/blob/master/k8s/us-central2/gcs-buckets.yaml)
* List new location:
```
gs://ml-auto-solutions/data/coco/
gs://ml-auto-solutions/data/criteo/
gs://ml-auto-solutions/data/imagenet/
gs://ml-auto-solutions/data/keras-api/
gs://ml-auto-solutions/data/kits19/
gs://ml-auto-solutions/data/liver-seg/
gs://ml-auto-solutions/data/mnist/
gs://ml-auto-solutions/data/ncf/
gs://ml-auto-solutions/data/old-bert/
gs://ml-auto-solutions/data/old-transformer/
gs://ml-auto-solutions/data/pretrain/
gs://ml-auto-solutions/data/shapemask/
gs://ml-auto-solutions/data/squad/ …
```

Update dataset locations after data migration

---

dags/solutions_team/configs/tensorflow/common.py

Migrated Keras repo from `xl-ml-test` to `cloud-ml-auto-solutions` ([link](https://source.cloud.google.com/cloud-ml-auto-solutions/tf2-api-tests)), so update project in codes accordingly.
Upload the change to Airflow and test Keras tests.
* One successful v2-8 run: [link](https://screenshot.googleplex.com/uip8FiatTxYtaPT)
* One successful v5e-4 run: [link](https://screenshot.googleplex.com/44NbVUzgUVatmuU)
* One successful v5p-8 run: [link](https://screenshot.googleplex.com/7CUQWJ7xthf7qYF)

Update project for Keras repo

---

.github/CODEOWNERS

Add code owner file to automatically assign required reviewer:
* example source - [link](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file)

Add code owner file

---

dags/solutions_team/configs/flax/solutionsteam_flax_latest_supported_config.py
dags/solutions_team/solutionsteam_flax_latest_supported.py

Add stable diffusion 2.1 model test on v5p per b/322223149, and also update 1.4 model to 2.1 for existing TPUs.
Upload to composer and test on Airflow.
Test [link](https://screenshot.googleplex.com/9P2CSgJasueEmZm)

Add stable diffusion 2.1 model test

---

dags/multipod/maxtext_end_to_end.py

As titled, add MaxText gpt3 test. 
Successfully run the following e2e test in a cloud vm.

Add MaxText tests for Gpt3

---

dags/multipod/maxtext_end_to_end.py

Adding a Llama2-7B finetuning test for both stable and nightly MaxText version
I have run all the MaxText tests in addition to this new test
Upload to Airflow, and test.
http://shortn/_1pw9SF5HJm

Add llama finetuning test

---

dags/multipod/configs/maxtext_gce_config.py

Update maxtext test as MXLA team requested, so step time will be > 1 sec.
https://screenshot.googleplex.com/WnsrSnPadsHhprz
https://screenshot.googleplex.com/9MoMmhPHWKEvRYJ

Update maxtext test as MXLA team requested

---

dags/pytorch_xla/configs/pytorchxla_torchbench_config.py
dags/pytorch_xla/pytorchxla_torchbench.py
dags/vm_resource.py
xlml/utils/gpu.py
xlml/utils/metric.py

1.  Add option to specify Nvidia driver version for torchbench;
2.  Enable H100, update location to use SSD to create VM;
3.  Fix metric.py issue when calling `provision.create_queued_resource.wait_for_ready_queued_resource`, which doesn't apply for GPU.
https://08398f98ca104983a06a424b851a390d-dot-us-central1.composer.googleusercontent.com/dags/pytorchxla-torchbench/grid
Let's see if this time we can pass all 7 platforms!

enable H100 test and add option to specify Nvidia driver version

---

dags/pytorch_xla/pytorchxla_torchbench.py

Simply update the A100 to use zone `us-central1-f`

update A100 to use us-central1-f

---

dags/multipod/configs/common.py
dags/multipod/configs/mxla_collective_config.py
dags/multipod/mxla_collective_nightly.py

Adding MXLA collective benchmark test.
Tested in local environment. 
https://screenshot.googleplex.com/AdYYtJxFaD2vJhf

Adding MXLA collective benchmark test

---

deployment/bigquery.auto.tfvars
deployment/bigquery_template.tf
deployment/cloud_composer_template.tf
xlml/utils/metric.py
xlml/utils/metric_test.py

Add dev datasets for data from dev stage:
* Update terraform to add dev datasets
* Update code to insert data to dev datasets
* Dataset: [link](https://screenshot.googleplex.com/3jCKJwbuRZFoJPy)
* Airflow run: [link](https://screenshot.googleplex.com/5VjRA4wYNUFagNu)

Add dev datasets for data from dev stage

---

dags/examples/maxtext_sweep_gce_example_dag.py
dags/examples/maxtext_sweep_gke_example_dag.py
dags/multipod/configs/maxtext_sweep_gce_config.py
dags/multipod/configs/maxtext_sweep_gke_config.py
xlml/apis/metric_config.py
xlml/apis/task.py
xlml/utils/metric.py
xlml/utils/metric_test.py
xlml/utils/name_format.py

* Add `prepend_tasks` and `append_tasks` attributes to `TpuQueuedResourceTask`, `TpuXpkTask`, `GpuCreateResourceTask` to allow prepending or appending custom tasks to the main job
* Add tasks to generate run name and tensorboard file location for MaxText jobs
* Enable metric processing to retrieve tensorboard file using regex
* Add test metadata (`project`, `accelerator`, etc.) when writing to BigQuery
* Ran in local composer environment
* maxtext_sweep_gce_example_dag: http://shortn/_gbZuZQ4rF3
* maxtext_sweep_gke_example_dag: http://shortn/_xS1vM6bOQG

Add maxtext sweep metrics collection

---

dags/multipod/configs/maxtext_gce_config.py

Update the maxtext nightly scripts to upload xplane files from all workers.
Tested in local env. 
https://screenshot.googleplex.com/73ZrQETjCHR6xog

Update the scripts to upload xplane files from all workers.

---

dags/legacy_test/tests/pytorch/experimental.libsonnet

This experimental option was remove recently in PyTorch/XLA.
n/a, backport of https://github.com/GoogleCloudPlatform/ml-testing-accelerators/pull/1045

Remove `TPU_C_API` env var

---

dags/pytorch_xla/configs/pytorchxla_torchbench_config.py

Stabilize the GPU freq for torchbench experiment based on https://github.com/pytorch/xla/blob/20692cb04256ca24b1dd2c7d00ffba0bb0cb69ac/benchmarks/nightly.sh#L127.

stablize GPU freq

---

docs/contributing.md

Set `pyink` version in docs

---

dags/pytorch_xla/configs/pytorchxla_torchbench_config.py
xlml/apis/metric_config.py
xlml/utils/metric.py

Reverts GoogleCloudPlatform/ml-auto-solutions#129

Revert "fix filename using timstamp changing issue and allow user to delete g…"

---

deployment/.terraform.lock.hcl
deployment/clusters.tf

Add GPU cluster to deployment config.
Applied config. Tested in PR that adds the tests: https://github.com/GoogleCloudPlatform/ml-auto-solutions/pull/111#issuecomment-1949326793

Add GPU clusters to deployments

---

deployment/cloud_composer_template.tf

Upgrade composer version with the [latest default version](https://screenshot.googleplex.com/AzmzAzhDR5Jpteb)
* next step: remove `KubernetesPodOperator` from xpk.py - [link](https://github.com/GoogleCloudPlatform/ml-auto-solutions/blob/master/xlml/utils/xpk.py#L50) 
N/A
* [link](https://screenshot.googleplex.com/7EJDLWhaqyRhMwj) of env 

Upgrade composer version

---

dags/multipod/maxtext_end_to_end.py

Renamed test_gamma.sh to test_gemma.sh
ran bash end_to_end/test_gemma.sh locally on TPU v4-8

Renamed test_gamma.sh to test_gemma.sh

---

dags/solutions_team/solutionsteam_tf_nightly_supported.py
dags/solutions_team/solutionsteam_tf_se_nightly_supported.py

Remove dummy operator in keras tests
Airflow: [tf_nightly](https://screenshot.googleplex.com/Ag425ZGkTApFAum), [tf_se_nightly](https://screenshot.googleplex.com/5PF947mmhLSVWxa)

Remove dummy operator for the TF test

---

dags/solutions_team/configs/pax/solutionsteam_pax_supported_config.py
dags/solutions_team/solutionsteam_pax_nightly_supported.py

Fixing several of the pax nightly tests
[link](http://shortn/_k3lFGZCCdK)
The screenshot above shows the three main changes to this PR.
(1), the convergence test passes with increased timeout
(2), the v5p-4 test was converted to v5p-8
(3), the v5p-16 test was converted to v5p-16

Pax nightly fixes

---

dags/solutions_team/solutionsteam_tf_2_16_se_supported.py
dags/solutions_team/solutionsteam_tf_2_16_supported.py

Currently, the system is stack of lots of queued tasks due to this dag name conflict due to this [merge](https://github.com/GoogleCloudPlatform/ml-auto-solutions/pull/137).
* [link](https://screenshot.googleplex.com/4KC5Fe9Q3GCDeE6)
* [link](https://screenshot.googleplex.com/9RGiVXCpNL65LvA)
Urgent fix dag name conflict to recover the system.

Urgent fix dag name conflict

---

dags/legacy_test/templates/tpus.libsonnet
dags/legacy_test/tests/pytorch/nightly/common.libsonnet
dags/legacy_test/tests/pytorch/nightly/resnet50-mp.libsonnet
dags/pytorch_xla/pytorchxla_torchvision.py
xlml/apis/test_config.py

Add example v5e test for PyTorch.
Screenshot from local run:
<details>
Note: I failed preprocess and cleanup manually so I could re-use this TPU after the test. Provision and run model work as expected.
</details>

[PT/XLA] Add ResNet v5e test

---

dags/pytorch_xla/pytorchxla_torchvision.py

Porting several existing variants of this test to the new system.
@JackCaoG let me know if there's another nightly variant that you want to add here.
Checked DAG construction:
<details>
</details>

[PT/XLA] Add many more ResNet50 tests

---

dags/infra/clean_up.py
xlml/utils/tpu.py

Clean up idle TPUs:
* Set TTL label to tpu provision timout + tpu run model timeout + 1 hour buffer time (provision, post_process, etc)
* Add task to clean up idle TPUs
Upload to airflow env and test
* Successfully attach ttl label: [link](https://screenshot.googleplex.com/8uvLmWPvmxWVTp8)
* Hard code a ttl to delete TPU: [link](https://screenshot.googleplex.com/59rz9NuBLiP7aEY), [link](https://screenshot.googleplex.com/AQrrx9YnmjnwPMu)
* Test no harm to TPUs that do not have ttl label

Clean up idle TPUs

---

.github/CODEOWNERS

Also add JSonnet tests to CODEOWNERS

---

dags/solutions_team/configs/tensorflow/common.py
dags/solutions_team/configs/tensorflow/solutionsteam_tf_2_16_supported_config.py

Fixes a bug where the git clone couldn't happen due to a permissions issue.
Successfully passing the setup step for resnet tests with this change.
**List links for your tests (use go/shortn-gen for any internal link):** http://shortn/_GGBSgj2Nk9

Fixes a permissions bug when cloning the models repo

---

dags/multipod/configs/maxtext_gce_config.py

https://screenshot.googleplex.com/4FF7JEEGer2i9QA

Skip first n steps for profiler

---

xlml/utils/tpu.py

Fix bug for deltatime:
* add node info in log during checking
Test it locally and Airflow
Airflow: [link](https://screenshot.googleplex.com/5rdRgx44vRRAdH3) 

Fix bug for deltatime

---

dags/solutions_team/solutionsteam_pax_nightly_supported.py

This PR fixes the `pax_nightly_lmcloudspmdadam-v4-16` test.
ran test locally http://shortn/_7uGiryvSWq

fix `pax_nightly_lmcloudspmdadam-v4-16` test

---

xlml/utils/metric.py

Forgot to update `metric.py` after updating provision stages for GPU. This causes issue in postprocess.
[torchbench(BERT_pytorch)](https://screenshot.googleplex.com/6zaDEYPdjY75G7p)

fix postprocess issue due to provision update

---

dags/legacy_test/tests/pytorch/nightly/llama2-model.libsonnet
dags/pytorch_xla/nightly.py

- Test was failing due to hardcoded path with wrong username: `No such file or directory: '/home/xl-ml-test/llama/7B/params.json'`
- Unravel the `echo`ing/`appending` to make the test easier to debug in the future
- Fix the double `-1vm` suffix
Tested locally (ignore post process failures):
<details>
</details>

[PT/XLA] Simplify and fix llama2 test

---

dags/legacy_test/tests/pytorch/nightly/ci.libsonnet
dags/legacy_test/tests/pytorch/nightly/targets.jsonnet
dags/legacy_test/tests/pytorch/r2.2/targets.jsonnet
dags/pytorch_xla/nightly.py

Combines these several tests from the old system.
Tested locally:
<details>
</details>

[PT/XLA] Run our CI script on v5lp nightly

---

dags/legacy_test/tests/pytorch/nightly/ci.libsonnet

Adjust the override order. Add missing `rich` dependency.
cc @lsy323 @zpcore 
Tested locally:
<details>
</details>

[PT/XLA] Add missing deps for CI test

---

dags/multipod/configs/gke_config.py
dags/multipod/mxla_maxtext_nightly.py
dags/multipod/mxla_maxtext_nightly_gke.py
dags/vm_resource.py

Migrate MXLA tests form GCE to GKE.
Pause all MXLA tests on GCE.
https://screenshot.googleplex.com/7oLS7GiPRgBSMav

Migrate MXLA tests form GCE to GKE.

---

dags/legacy_test/tests/pytorch/r2.3/accelerate-smoke.libsonnet
dags/legacy_test/tests/pytorch/r2.3/ci.libsonnet
dags/legacy_test/tests/pytorch/r2.3/common.libsonnet
dags/legacy_test/tests/pytorch/r2.3/hf-bert.libsonnet
dags/legacy_test/tests/pytorch/r2.3/hf-diffusers.libsonnet
dags/legacy_test/tests/pytorch/r2.3/llama2-model.libsonnet
dags/legacy_test/tests/pytorch/r2.3/mnist.libsonnet
dags/legacy_test/tests/pytorch/r2.3/resnet50-mp.libsonnet
dags/legacy_test/tests/pytorch/r2.3/targets.jsonnet
dags/legacy_test/tests/pytorch/targets.jsonnet
dags/pytorch_xla/r2_3.py

Add pytorch/xla r2.3-rc2 tests
- The jsonnet test files are copied from nightly test.
- Set running schedule to None, so the new test sets won't run periodically. It can be triggered manually.
- Updated the script to install 2.3-rc2 torch, torch/xla whl and the compatible torchvision.
Testing with setting up local Airflow. But failed with unknown error during `setup` stage.

Add pytorch/xla r2.3-rc2 tests

---

dags/multipod/configs/gke_config.py

Add network settings to MXLA perf tests to improve the multislice performance 
https://screenshot.googleplex.com/7uzrwhv5MCLu4er

Add network settings to MXLA perf tests.

---

dags/legacy_test/tests/pytorch/r2.3/common.libsonnet

Copy test scripts from release tag. Before this PR, the tests are copied from `master` branch, which may not be compatible with the r2.3 branch.
Done locally.

copy test scripts from release tag

---

.github/CODEOWNERS

Update the owner for pytorch repo.

update pytorch owner

---

dags/multipod/configs/gke_config.py
dags/multipod/mxla_gpt3_6b_nightly_gke.py

Add GPT3-6B nightly tests for MXLA.
https://screenshot.googleplex.com/8EZzhXX7zFLB7CS

Add GPT3-6B nightly tests for MXLA.

---

dags/pytorch_xla/configs/pytorchxla_torchbench_config.py
dags/pytorch_xla/pytorchxla-torchbench-release.py

Support for torchbench experiment on torch_xla releases.
Note: Don't trigger the run in prod env yet since this will contaminate the results of nightly run.
https://402f31b802dc42918d8712d630ea643a-dot-us-central1.composer.googleusercontent.com/dags/pytorchxla-torchbench-release/grid

add dag job to support release test

---

dags/multipod/maxtext_profiling.py
dags/test_owner.py

Add MaxText stable and nightly profiling tests.
Ran the tests locally: http://shortn/_9b98QFU9fh

Add MaxText stable and nightly profiling test

---

dags/solutions_team/configs/tensorflow/common.py

Comma was included in the prior run but I forgot to amend the commit
This was the code that was run in https://github.com/GoogleCloudPlatform/ml-auto-solutions/pull/214
http://shortn/_RBZjspOxFM

Add missing comma

---

dags/pytorch_xla/nightly.py
dags/pytorch_xla/r2_3.py

Disable PyTorch/XLA diffusers tests.
N/A

Disable PyTorch/XLA diffusers tests.

---

dags/legacy_test/tests/pytorch/nightly/llama2-model.libsonnet

Logging change for PTXLA llama2 test.
N/A

Logging change for PTXLA llama2 test

---

.github/requirements.txt
deployment/cloud_composer_template.tf

It seems PyArrow was a required transitive dependency, which broke our CI.
CI

Add pyarrow explicitly

---

xlml/utils/xpk.py

GPU tests were broken by the last change, which enables GCS output path and log printing.
This change will depend on https://github.com/google/xpk/pull/104 to add `--env` support in XPK.
Ran a local XPK test (did not have permissions to test in the GPU project):
- https://screenshot.googleplex.com/Kmw4s83FgKnXUBx

Disable log printing GPU and set GCS output using `--env`

---

dags/legacy_test/tests/pytorch/nightly/common.libsonnet
dags/legacy_test/tests/pytorch/r2.3/common.libsonnet

Accelerate tests need `pytest` dependency now. There is no `requirements.txt` in Accelerate repo, so I have to install it in the setup script
Local test in dev env.

Add pytest dependency to accelerate tests

---

dags/multipod/legacy.py
dags/test_owner.py

Multipod test for [pedagogical_examples/shardings.py](https://github.com/google/maxtext/blob/main/pedagogical_examples/shardings.py)
Ran it locally: screen/3ZYPPzrToSRBDdw

MaxText shardings.py test

---

dags/legacy_test/tests/pytorch/r2.3/common.libsonnet

Update 2.3 tests to use 2.3.0rc6 image/whl
WIP test locally

Update torch_xla r2.3 test for v2.3.0-rc6

---

dags/multipod/maxtext_end_to_end.py

Change Gemma test path
Ran locally: screen/A8M6sUEut8rzwJt

[MaxText] Change Gemma test path

---

.pylintrc
dags/vm_resource.py
scripts/code-style.sh
xlml/apis/gcp_config.py
xlml/apis/metric_config.py
xlml/apis/task.py
xlml/apis/test_config.py
xlml/utils/bigquery.py
xlml/utils/bigquery_test.py
xlml/utils/gke.py
xlml/utils/gpu.py
xlml/utils/metric_test.py
xlml/utils/tpu.py
xlml/utils/xpk.py

Increase fail score for pylint from 9 to 9.6.
Expect all checks pass.

Increase fail score for pylint

---

dags/legacy_test/tests/pytorch/r2.3/common.libsonnet

Update 2.3 tests to use 2.3.0rc12 image/whl
Test full test suite in dev env.

Update torch_xla r2.3 test for v2.3.0-rc12

---

dags/multipod/maxtext_end_to_end.py

Based on maxtext PR: https://github.com/google/maxtext/pull/578. We will separate tpu and gpu scripts for end-to-end testing.
https://540cef12d3da42ce97b48a97401b6c83-dot-us-central1.composer.googleusercontent.com/dags/maxtext_end_to_end/grid?dag_run_id=manual__2024-04-11T02%3A04%3A51.094374%2B00%3A00&tab=graph

separate gpu and tpu scripts for end-to-end testing

---

dags/multipod/configs/maxtext_gce_config.py
dags/multipod/legacy.py
dags/multipod/maxtext_checkpointing.py
dags/multipod/maxtext_convergence.py

New TPU paths for maxtext end-to-end tests
maxtext_checkpointing: https://540cef12d3da42ce97b48a97401b6c83-dot-us-central1.composer.googleusercontent.com/dags/maxtext_checkpointing/grid
maxtext_convergence: https://540cef12d3da42ce97b48a97401b6c83-dot-us-central1.composer.googleusercontent.com/dags/maxtext_convergence/grid

New path for tpu end-to-end tests

---

dags/multipod/legacy.py

Fix shardings test arguments
Ran locally 
https://screenshot.googleplex.com/AnGmaESVmbPMRj7

Fix shardings test arguments

---

deployment/cloud_composer_template.tf

Add Service Account Admin and Project IAM Admin role to the service account that will run the Airflow tests
This is required for the new changes in XPK: https://github.com/google/xpk/pull/86
- [y] I have performed a self-review of my code.
- [y] I have necessary comments in my code, particularly in hard-to-understand areas.
- [y] I have run one-shot tests and provided workload links above if applicable. 
- [y] I have made or will make corresponding changes to the doc if needed.

Add Service Account Admin and Project IAM Admin role

---

.github/workflows/dag-check.yml
.github/workflows/pyink-check.yml
.github/workflows/pylint-check.yml
.github/workflows/unit-test.yml
.pre-commit-config.yaml

* Update Python version to 3.11 for workflows that match composer env version - composer env is `composer-2.6.1`, and Python version is 3.11 - [link](https://screenshot.googleplex.com/Piay263rUL5ZerT)
* Update language_version to avoid pre-commit error during git push.
Expect all tests pass.
Expect all tests pass.

Update Python version

---

.github/CODEOWNERS

Update CODEOWNERS for inference

---

dags/multipod/configs/gke_config.py
dags/multipod/maxtext_end_to_end.py
dags/test_owner.py
dags/vm_resource.py
xlml/apis/metric_config.py
xlml/apis/task.py
xlml/apis/test_config.py

Adding multi-cluster maxtext tests
Instruction and/or command lines to reproduce your tests: ...
Upload to airflow and test.
[link for chained job 1](https://screenshot.googleplex.com/3zNKwj4gaiV5oNV)
[link for chained job 2](https://screenshot.googleplex.com/7q6oE5egKygDXZP)

Anisha add gemma7b test

---

dags/multipod/maxtext_v4_configs_aot_hybridsim.py

Add AOT + HybridSim tests for MaxText v4 configs
Tested in local Composer env: http://shortn/_ILuRzE2MUb

Add AOT + HybridSim tests for MaxText v4 configs

---

dags/multipod/configs/gke_config.py
dags/multipod/maxtext_v4_configs_aot_hybridsim.py
xlml/apis/task.py

Adding result collection to AOT + HybridSim MaxText test. The HybridSim estimation gets printed out to the logs and is then parsed by the test script that writes it to a json lines file in GCS for XLML to process.
Ran in local Composer env: http://screen/9LqbTxy2MNdUL7w

Add result collection to AOT + HybridSim MaxText test

---

dags/solutions_team/configs/tensorflow/common.py

Our nightly TF whl is currently running into an odd seg fault when tensorflow is imported which is preventing all of our tests from running. This change uses the Tensorflow team's nightly whl as a stop-gap solution while we work to fix our build.
It's also possible we make this change permanent if there's no good reason to maintain our own build but that decision is TBD.
Sample test that is now passing with this change: http://shortn/_gu6F9p5Vhx
- [ X ] I have made or will make corresponding changes …

Using tensorflow team's nightly tf whl as a stopgap

---

dags/multipod/maxtext_convergence.py

Add convergence test for subset of hosts dataloading
Link to the test run https://cloudlogging.app.goo.gl/Fjp92WP4bTKwCkH8A

[MaxText] Add convergence test for subset of hosts dataloading

---

.github/CODEOWNERS

This one Jax test was missing from Shiva's ownership, added it to her.
N/A

Adding Test Owners for Top-Level Solutions Team Directory

---

dags/multipod/maxtext_end_to_end.py
dags/vm_resource.py

Fix previous bug of resolving conflicts incorrectly.
Add pinned image for gpu testing
Manually tested on Airflow
https://540cef12d3da42ce97b48a97401b6c83-dot-us-central1.composer.googleusercontent.com/dags/maxtext_end_to_end/grid?dag_run_id=manual__2024-04-30T03%3A05%3A27.182058%2B00%3A00&task_id=maxtext-stable-llama2-7b-h100-80gb-8.run_model.launch_workload.run_workload&tab=logs

Fix previous bug and Add pinned image for GPU end-to-end testings

---

dags/multipod/maxtext_configs_aot_hybridsim.py

Add v5e configs to aot+hybridsim test.
Ran in local composer env: http://screen/5WW5rev3AH6LBuB

Add v5e configs to aot+hybridsim test

---

dags/multipod/maxtext_end_to_end.py

Adding Llama2-70b multicluster tests
[MaxText PR](https://github.com/google/maxtext/pull/639)
Tested using local composer environment and also on XPK manually
http://shortn/_RPMgAGUTPV
http://shortn/_lZOrmPCMg3
http://shortn/_mtJzuxANQY
- [ X] I have performed a self-review of my code.
- [ X] I have necessary comments in my code, particularly in hard-to-understand areas.
- [ X] I have run one-shot tests and provided workload links above if applicable. 
- [ X] I have made or will make corresponding changes to the doc if needed.

Add llama2-70b

---

dags/inference/configs/maxtext_inference_gce_config.py

Add ICI-related metrics to be uploaded to BigQuery. This should be done after https://github.com/google/JetStream/pull/77 is merged.
Ran in my dev composer environment, and see successful write to my dev BigQuery table.

Add ICI-related metrics

---

dags/multipod/maxtext_configs_aot_hybridsim.py
dags/vm_resource.py

Add hybridsim nightly image
Ran in local Composer env: http://screen/8QrQJ2x8xw73JmM

Add hybridsim nightly image

---

dags/multipod/maxtext_configs_aot_hybridsim.py

Add 4, 8 slices to hybridsim test
Ran in local Composer env: https://screenshot.googleplex.com/W7SBPGpgnsyDhFy

Add 4, 8 slice simulation to hybridsim test

---

dags/inference/configs/maxtext_inference_gce_config.py
dags/inference/maxtext_inference.py

Add ability to specify and track the model's precision (`weight_dtype`).

Specify and track model precision

---

dags/multipod/configs/gke_config.py
dags/multipod/maxtext_end_to_end.py

Added additional set of e2e tests for MaxText on GPU, which was being run as part of Github CI cycle. 
e2e tests for MaxText on GPU, which was being run as part of Github CI cycle. 
http://shortn/_xbaeeGenAU

Add maxtext e2e gpu tests

---

dags/pytorch_xla/configs/pytorchxla_torchbench_config.py
dags/pytorch_xla/nightly.py
dags/pytorch_xla/pytorchxla-torchbench-release.py
dags/pytorch_xla/pytorchxla_torchbench.py
dags/pytorch_xla/r2_3.py
dags/vm_resource.py
xlml/apis/gcp_config.py
xlml/apis/task.py
xlml/apis/test_config.py
xlml/utils/gke.py
xlml/utils/metric.py

1. Modify GKE to support storing result to GCS and postprocess data;
2. Update torchbench to use GKE;
3. [Minor] Update r2.3 release test dependency.
Currently only support V100. Will add H100, L4 and A100.
[Torchbench using GKE on V100](https://60bb71acc6784780b3bbdbae4ffa636f-dot-us-central1.composer.googleusercontent.com/dags/pytorchxla-torchbench/grid?dag_run_id=manual__2024-05-16T23%3A54%3A36.254218%2B00%3A00&task_id=torchbench_BERT_pytorch-v4-8&tab=graph)
[Jsonline config test](https://60bb71acc6784780b3bbdbae4ffa636f-dot-us-central1.composer.googleusercontent.com/dags/pytorchxla-nightly/grid?dag_run_id=manual__2024-05-21T21%3A32%3A18.524828%2B00%3A00&task_id=pt-nightly-resnet50-mp-plugin-fake-v100-x2x1-nvidia-tesla-v100)
Before submitting this PR, please make sure (put X in square …

Support GKE for torchbench

---

.github/CODEOWNERS

Add ZhaoyueCheng as owner of TF tests
Owner change

add Zhaoyue as owner of the TF tests

---

xlml/utils/gke.py

Currently this either returns success if there is no exception and no status, or it starts a new attempt if there is an exception.
Tested locally. Jobs are failing if the sensor retries after the `job_create_timeout`, even if they're within the test config's `timeout`. Needs follow-up.

Retry GKE `stream_logs` when status is unkown

---

dags/solutions_team/configs/tensorflow/solutionsteam_tf_nightly_supported_config.py
dags/solutions_team/configs/tensorflow/solutionsteam_tf_release_supported_config.py

Fix ResNet singlehost and multihost issues (adjust batch size and fix internal runtime version configs)
ResNet v4-8 and v4-32
Run local airflow test for resnet
Both ResNet single host and multihost tests are successful
screen/8euWqUbu7VeGyo8

Adjust batch_size to 2048 for resnet tests

---

dags/imagegen_devx/configs/project_bite_config.py
dags/imagegen_devx/project_bite.py

Add pinned version fuji test:
* Update set up helper functions
* Add functionality to run pinned version of axlearn repo
Test - [link](https://screenshot.googleplex.com/8aq4m7MANydLJjS)

Add pinned version fuji test

---

.github/CODEOWNERS

Update inference owners

---

dags/multipod/maxtext_profiling_vertex_ai_tensorboard.py
xlml/apis/task.py
xlml/utils/xpk.py

This PR adds a test to check that MaxText profile has been uploaded to Vertex AI Tensorboard instance.
- Ran local airflow server to verify that the DAG is up and running
- The tests are failing currently for a known reason and we are working on fixing it

Add tests for MaxText automatic profile upload to Vertex AI Tensorboard

---

deployment/clusters.tf

Add H100 cluster from `cloud-ml-benchmarking` project.
(See my comments for terraform plan output)

add cross project H100 cluster

---

deployment/clusters.tf

Quick fix gke naming issue to lower case.

change to lower case

---

dags/multipod/maxtext_end_to_end.py
dags/vm_resource.py
xlml/utils/xpk.py

Run GPU e2e tests on A3+ cluster

---

dags/pytorch_xla/configs/pytorchxla_torchbench_config.py
dags/pytorch_xla/pytorchxla_torchbench.py
dags/vm_resource.py

1) Use GPU (A100, L4, H100, V100) from `cloud-ml-benchmarking` project.
2) Switch all GPU from GCE to GKE.
Torchbench test [here](https://60bb71acc6784780b3bbdbae4ffa636f-dot-us-central1.composer.googleusercontent.com/dags/pytorchxla-torchbench/grid?dag_run_id=manual__2024-06-11T06%3A40%3A52.525796%2B00%3A00&task_id=torchbench-bert-pytorch-nvidia-tesla-a100.run_model.stream_logs&tab=logs).
The test fail due to two issues: 1) GKE stream log listener sensor timeout issue 2) experiment output use bool format. I am working on a PR for pytorch/XLA for the fix. 
Those are irrelevant to this PR.

Use external resource for torchbench

---

dags/inference/configs/maxtext_inference_gce_config.py

Update arg to Jetstream benchmark due to changes in https://github.com/google/maxtext/pull/692

Update jetstream benchmark config file

---

.gitignore
dags/inference/configs/maxtext_inference_microbenchmark_gce_config.py
dags/inference/maxtext_inference_microbenchmark.py
dags/test_owner.py

MaxText Inference MicroBenchmark to test best KV cache & sharding configurations.

MaxText Inference MicroBenchmark

---

dags/legacy_test/tests/pytorch/r2.4/common.libsonnet

Update PyTorch/XLA 2.4 release version for tests

---

dags/multipod/maxtext_v5e_configs_perf.py

Add MaxText Llama2 7B, 13B, 70B to v5e perf tests
Ran in local Composer env: https://screenshot.googleplex.com/BaPbwkw755Di5EJ

Add MaxText Llama2 to v5e perf tests

---

dags/multipod/maxtext_v5e_configs_perf.py

Add dependencies between v5e perf tests
N/A

Add dependencies between v5e perf tests

---

.github/CODEOWNERS
dags/inference/jetstream_pytorch_inference.py

add @sixiang-google to codeowners

---

dags/legacy_test/tests/pytorch/r2.4/common.libsonnet

Update Pytorch/XLA 2.4 release wheel to rc8

---

dags/legacy_test/tests/pytorch/r2.4/llama2-model.libsonnet

Fix permissions for PT/XLA 2.4 release tests

---

.github/CODEOWNERS

Add my github to inference code owners.

Add to inference code owners

---

dags/pytorch_xla/configs/pytorchxla_torchbench_config.py
dags/pytorch_xla/pytorchxla-torchbench-release.py

1. Add the 2.4 release test;  
2. Fix setup tool version issue https://github.com/pypa/setuptools/issues/4483
Test [link](https://60bb71acc6784780b3bbdbae4ffa636f-dot-us-central1.composer.googleusercontent.com/dags/pytorchxla-torchbench-release/grid?dag_run_id=manual__2024-07-23T05%3A30%3A43.058198%2B00%3A00&tab=graph).

add r2.4 test and fix setuptool version

---

dags/legacy_test/tests/pytorch/nightly/common.libsonnet
dags/pytorch_xla/configs/pytorchxla_torchbench_config.py

See https://github.com/pytorch/xla/pull/7736

Remove references to `torch_xla[tpuvm]` optional dependency

---

dags/multipod/configs/common.py
dags/multipod/configs/maxtext_gce_config.py
dags/multipod/mxla_maxtext_nightly.py

Adding temp MXLA test for v5p GA as requested.
Please ignore the simple implementation since this test will be removed after v5p GA.
http://shortn/_AhgdRdxWqI

Adding temp MXLA test for v5p GA as requested.

---

dags/multipod/maxtext_v5e_configs_perf.py
dags/solutions_team/configs/tensorflow/common.py
dags/solutions_team/configs/tensorflow/solutionsteam_tf_nightly_supported_config.py
dags/solutions_team/solutionsteam_tf_nightly_supported.py

Fix TF DLRM setup for pod tests 
Test passed - screen/9n3XFWQNpCGBka3

Fix setup instructions for TF DLRM model 

---

dags/multipod/maxtext_configs_aot_hybridsim.py

JAX Stable Stack Docker Image for AOT Hybridsim Tests
Verified on XLML

JAX Stable Stack Docker Image for AOT Hybridsim Tests

---

dags/solutions_team/configs/tensorflow/common.py
dags/solutions_team/configs/tensorflow/solutionsteam_tf_nightly_supported_config.py
dags/solutions_team/solutionsteam_tf_se_nightly_supported.py

Remove libtpu lockfile before reloading tpu-runtime
passing dlrm tests - screen/4HHRoiAncnLTt7r

Remove libtpu lockfile before reloading tpu-runtime

---

dags/imagegen_devx/jax_stable_stack_e2e.py

- Fixing breaking tests after Maxdiffusion refactoring
- Removing maxtext unstable cluster config

Fixing JAX Stable Stack end-to-end breaking tests 

---

dags/imagegen_devx/jax_stable_stack_e2e.py

Modifying maxdiffusion training command to be compatible with the latest version of maxdiffusion
https://c3aed121fd4247389a3ca4b9c5878779-dot-us-east4.composer.googleusercontent.com/dags/jax_stable_stack_e2e/grid

Modifying maxdiffusion training command to be compatible with the latest version of maxdiffusion

---

dags/multipod/maxtext_v5e_configs_perf.py
xlml/apis/task.py
xlml/utils/xpk.py

Add pathways v5e perf tests

---

dags/multipod/maxtext_trillium_configs_perf.py
dags/multipod/maxtext_v5e_configs_perf.py
dags/vm_resource.py

Add MaxText perf tests on trillium.
Ran in local environment https://screenshot.googleplex.com/8VvNoiyFmddzxgV

Add MaxText perf tests on trillium

---

xlml/utils/name_format.py

Update tensorboard file location due to https://github.com/google/maxtext/pull/863 for max* runs 

Fix max* tensorboard file location

---

dags/imagegen_devx/maxdiffusion_e2e.py

Adding maxdiffusion test to assert training loss.  The test fails if the training loss value is below a particular threshold. This test is useful for verifying NaN loss. 

Adding maxdiffusion test to assert training loss

---

dags/multipod/maxtext_end_to_end.py

Remove dangling Jax Stable Stack task group.
As part of 

Remove dangling Jax Stable Stack task group

---

dags/inference/configs/jetstream_pytorch_gce_config.py
dags/inference/jetstream_pytorch_inference.py

Fix for resource congestion & add tests with different batch sizes

---

dags/vm_resource.py

Fix device type in v5e cluster

---

dags/framework3p/configs/microbenchmarks_config.py
dags/framework3p/microbenchmarks_dag.py
dags/test_owner.py
dags/vm_resource.py

Create DAGs for microbenchmarks for v5e and v4p.
Ran the framework_microbenchmarks dag in airflow: https://pantheon.corp.google.com/composer/dags/us-central1/ml-automation-solutions-dev/framework_microbenchmark/runs?referrer=search&e=HybridGceDiskLaunch::HybridGceDiskDisabled,HybridGceSnapshotLaunch::HybridGceSnapshotDisabled&invt=Abc0cw&mods=logs_tg_test&project=cloud-ml-auto-solutions&pageState=(%22taskInstanceList%22:(%22f%22:%22%255B%255D%22))

Create DAGs for microbenchmarks

---

dags/multipod/maxtext_end_to_end.py

This PR points to a new end-to-end Mistral test, submitted as part of https://github.com/AI-Hypercomputer/maxtext/pull/903

Update test workflow to use the new mistral end-to-end script.

---

dags/inference/maxtext_inference.py

Add different batch sizes for llama and gemma

---

dags/vm_resource.py

The old A3 cluster is gone, created new A3 cluster for testing. Change the name and zone of A3 cluster.
Test on nina_dags airflow.
Run dags check.
https://540cef12d3da42ce97b48a97401b6c83-dot-us-central1.composer.googleusercontent.com/dags/maxtext_gpu_end_to_end/grid

Change a3 cluster and its zone

---

.github/CODEOWNERS
dags/imagegen_devx/jax_stable_stack_e2e.py
dags/imagegen_devx/maxdiffusion_e2e.py
dags/vm_resource.py

- Fixing incorrect build image path 
- Changing command to run maxdiffusion based on https://github.com/AI-Hypercomputer/maxdiffusion/pull/107

Fixing test images and run command

---

dags/inference/configs/jetstream_pytorch_gce_config.py
dags/inference/jetstream_pytorch_inference.py

Change configs for inference dashboard & adjust num_prompts

---

dags/imagegen_devx/jax_stable_stack_e2e.py
dags/imagegen_devx/maxdiffusion_e2e.py

The command contained `python install .` instead of `pip install .` which was causing the tests to fail. 

Fixing incorrect command which is causing tests to fail

---

dags/legacy_test/tests/pytorch/r2.5/common.libsonnet
dags/pytorch_xla/configs/pytorchxla_torchbench_config.py

update PyTorch/XLA 2.5 benchmarking with rc5 wheel
update PyTorch/XLA 2.5 release benchmarking tests with rc5 wheel

Update PyTorch/XLA r2.5 benchmarking with rc5 wheel

---

dags/pytorch_xla/r2_5.py

update to 2-5 for v6e test name
name string change

update to 2-5 for v6e test name

---

dags/imagegen_devx/maxdiffusion_e2e.py

Running maxdiffusion on 2 slices of v4-8

Adding a multislice test for maxdiffusion 

---

dags/legacy_test/tests/pytorch/r2.5/common.libsonnet
dags/pytorch_xla/configs/pytorchxla_torchbench_config.py

update PyTorch/XLA 2.5 benchmarking with rc9 wheel
update PyTorch/XLA 2.5 release benchmarking tests with rc9 wheel

Update PyTorch/XLA r2.5 benchmarking with rc9 wheel

---

.github/CODEOWNERS

Removing myself as default code owner. @RissyRan @allenwang28 please merge after you get back from vacation next week.
FYI @jonb377 I removed you as an owner of the PyTorch tests

Clean up code owners

---

dags/inference/jetstream_pytorch_inference.py

Add trillium to jetstream-pytorch tests

---

dags/legacy_test/tests/pytorch/r2.5/llama2-model.libsonnet
dags/pytorch_xla/r2_5.py

[Testing] add llama3-8

---

dags/pytorch_xla/nightly.py

Update the v5p capacity for night CI
[test link](https://60bb71acc6784780b3bbdbae4ffa636f-dot-us-central1.composer.googleusercontent.com/dags/pytorchxla-nightly/grid?dag_run_id=manual__2024-10-15T00%3A43%3A44.861037%2B00%3A00&task_id=pt-nightly-ci-func-v5p-8-1vm.run_model)

Update v5p project for nightly.py

---

dags/legacy_test/tests/pytorch/r2.5/common.libsonnet
dags/pytorch_xla/configs/pytorchxla_torchbench_config.py

Update PyTorch/XLA r2.5 benchmarking with rc10 wheel

---

dags/inference/configs/jetstream_pytorch_gce_config.py
dags/inference/jetstream_pytorch_inference.py

Modified setup and run model cmds to accomodate latest jetstream-pt change

---

dags/imagegen_devx/project_bite.py

Update pinned version to Oct 16, 2024 - [commit source](https://screenshot.googleplex.com/6Bg6ct9We3hWCft).
XL ML nightly tests
Test passed for nightly: [link](https://screenshot.googleplex.com/4w4tw2sTuU5AnCt)

Update pinned version of axlearn

---

dags/legacy_test/tests/pytorch/r2.5/common.libsonnet
dags/pytorch_xla/configs/pytorchxla_torchbench_config.py

update r2.5 branch test with 2.5.0 final wheel

Update common.libsonnet to 2.5.0

---

dags/multipod/maxtext_convergence.py

Add grain and hf pipeline to convergence test.
I followed the instruction here to test locally: https://github.com/GoogleCloudPlatform/ml-auto-solutions/blob/master/docs/contributing.md#testing-changes-locally 
Local test doesn't have a shareable link. This screenshot shows the workload runs successfully (https://screenshot.googleplex.com/BMJQc3kNvR6uEvQ). But all my 3 tests failed post processing with the same error. I did not make any change to the first test (it's passing in the current nightly …

add data pipeline to convergence test

---

dags/multipod/maxtext_trillium_configs_perf.py
dags/vm_resource.py

Update trillium test cluster
N/A

Update trillium test cluster

---

dags/imagegen_devx/configs/gke_config.py
dags/imagegen_devx/jax_stable_stack_e2e.py

Add Trillium configuration for JAX Stable Stack DAG
[Please describe the tests that you ran on Cloud VM to verify changes.
](https://screenshot.googleplex.com/3eR6kiFivmp2tXc)

Trillium Support for JAX Stable Stack DAG

---

dags/imagegen_devx/maxdiffusion_e2e.py

- Added multi-slice trillium configuration
- Changed the image to point to stable stack 

Adding multislice configuration

---

dags/multipod/maxtext_trillium_configs_perf.py

Add Llama2-70b-4096 and Mixtral-8x7b trillium regression tests via XPK

Add Llama2-70b-4096 and Mixtral-8x7b XPK regression tests

---

dags/vm_resource.py

Change v6e XPK MaxText regression test cluster

Change v6e XPK MaxText regression test cluster

---

dags/legacy_test/tests/pytorch/r2.5.1/common.libsonnet
dags/pytorch_xla/configs/pytorchxla_torchbench_config.py

Update tests for PyTorch/XLA 2.5.1 release

[PyTorch/XLA 2.5.1 release] Update common.libsonnet for v2.5.1

---

dags/pytorch_xla/configs/pytorchxla_torchbench_config.py

Update pytorchxla_torchbench_config.py to 2.5.1 for GPU

[PyTorch/XLA 2.5.1 release] Update pytorchxla_torchbench_config.py to 2.5.1 for GPU

---

dags/inference/configs/trt_llm_mlperf_v40_config.py
dags/inference/trt_llm_mlperf_v41_inference.py

Fix the recent trt-llm DAG issues. 
https://screenshot.googleplex.com/4VyXfYP74xARWSW
https://screenshot.googleplex.com/6vpjswmsdn4q7Km

Fix trt-llm GPU Inference DAG Failure

---

.github/CODEOWNERS

Updating Owners

---

dags/imagegen_devx/jax_stable_stack_e2e.py
dags/imagegen_devx/jax_stable_stack_gpu_e2e.py
dags/imagegen_devx/jax_stable_stack_tpu_e2e.py
dags/vm_resource.py

Splitting JAX Stable Stack DAGs to TPU and GPU for better on-duty monitoring

Splitting JAX Stable Stack DAGs to TPU and GPU

---

dags/multipod/jax_functional_tests.py

Run the Jax.distributed.initialize() test on nightly, stable and stable stack JAX versions
Tested on the dev branch: http://shortn/_WUwhuAqJfm

Run the GCE JAX test on nightly, stable and stable stack

---

dags/imagegen_devx/configs/gke_config.py
dags/imagegen_devx/jax_stable_stack_gpu_e2e.py
dags/imagegen_devx/jax_stable_stack_tpu_e2e.py
dags/imagegen_devx/project_bite_gpu_e2e.py
dags/imagegen_devx/project_bite_tpu_e2e.py
dags/vm_resource.py

Adding AxLearn workload for stable stack e2e test
Verified on local cluster. **Note** the tests take a long time to complete 

Adding AxLearn workload for stable stack e2e test

---

.github/CODEOWNERS

Add new owner to the repo
Expect all unit tests pass.

Add new owner to the repo

---

dags/multipod/maxtext_trillium_configs_perf.py
dags/multipod/maxtext_v5e_configs_perf.py
dags/quarantined_tests.py
xlml/apis/task.py

Adding a quarantine folder for remaining multipod DAGs.

Adding a quarantine folder for remaining multipod DAGs

---

dags/quarantined_tests.py
dags/sparsity_diffusion_devx/jax_stable_stack_gpu_e2e.py
dags/sparsity_diffusion_devx/maxtext_moe_tpu_e2e.py
dags/sparsity_diffusion_devx/project_bite_gpu_e2e.py
dags/sparsity_diffusion_devx/project_bite_tpu_e2e.py

* Split/Move MoE Mixtral tests from MaxText end-to-end tests for convenient monitoring
* Update and align DAG labels for the team
* Next step - fix those failures
Upload changes to composer environment and test
* Able to trigger MoE tests: [link](https://screenshot.googleplex.com/5uZy4RxxBjYgnxe)
* Removed MoE tests in MaxText end-to-end: [link](https://screenshot.googleplex.com/4in7JLEYQsPQyGo) 

Split MoE from end_to_end test

---

dags/sparsity_diffusion_devx/jax_stable_stack_gpu_e2e.py
dags/sparsity_diffusion_devx/jax_stable_stack_tpu_e2e.py
dags/vm_resource.py

- Adding new tests for Stable Stack with JAX nightly 
- Renaming images
Tested on local cloud VM

Adding new tests with stable stack nightly jax images

---

.github/CODEOWNERS

Update CODEOWNERS - add richardsliu as owner

---

deployment/modules/composer_env/main.tf

Fix b/381092874 to trigger XPK workloads
Upload to dev composer environment, and test.
Load the head codes, and triggering is find now: [link](https://screenshot.googleplex.com/6B3wM3JJKpKGqeb)

Add ruamel dependency

---

dags/solutions_team/solutionsteam_tf_nightly_supported.py

Updating TF runtime environment for v4-32 in nightly test

Fix one test for nightly

---

dags/map_reproducibility/nemo_gpt3.py
dags/map_reproducibility/utils.py

Fix helm chart name as it was changed in the repo
Ran on test composer env

fix current DAG

---

dags/map_reproducibility/nemo_gpt3.py

Update prod benchmark DB table with regression tests
Test composer 

turn off is_test

---

dags/map_reproducibility/utils.py

Minor fix to remove change of directory
Test composer

remove change in dir in cleanup

---

dags/composer_env.py
deployment/modules/composer_env/main.tf

Update composer environment to 2.10.1

Update composer environment to 2.10.1

---

dags/common/vm_resource.py

Update MaxText Stable Stack docker image path

Update MaxText JAX StS path

---

dags/map_reproducibility/a3mega_gpt3_175b_nemo.py
dags/map_reproducibility/a3ultra_mixtral_nemo.py
dags/map_reproducibility/utils/benchmarkdb_utils.py
dags/map_reproducibility/utils/common_utils.py

Change bq writer path and generalize more
test comp

Change bq writer path

---

.github/CODEOWNERS

Add team member to code owner

---

dags/common/vm_resource.py

Update to new shared v5e cluster based on http://b/387365963
N/A

Update shared v5e cluster

---

dags/legacy_test/tests/pytorch/r2.6/common.libsonnet

And when we cut the next rc wheel, it will also use the corresponding tag.

[torch_xla] Test 2.6rc3 wheel against 2.6rc3 tag

---

dags/solutions_team/configs/tensorflow/solutionsteam_tf_nightly_supported_config.py

fix DLRM single host test
DLRM single host test on v5p
screen/7etozAxS6QsunUZ

fix DLRM single host test

---

dags/multipod/configs/maxtext_sweep_gke_config.py

Update run name based on quantization type
* Add a function to update run name prefix b/388584410
Upload to airflow and test
* before the change: [link](https://screenshot.googleplex.com/By4i5igcNfMcuD7)
* after the change: [link](https://screenshot.googleplex.com/BvHYMRVGv3hZhky)

Update run name based on quantization type

---

dags/multipod/maxtext_configs_aot_hybridsim.py

Add xla_dump_large_constants flag to AOT script in HybridSim test http://b/380921517
Ran the v4 tests https://screenshot.googleplex.com/niFFMjPKmkfveJn

Add xla_dump_large_constants flag to AOT script in HybridSim test

---

dags/common/vm_resource.py

Update v5p-8 cluster
Ran in my local airflow, yesterday ran into error due to old jobset, should be now fixed. Can't run tests today successfully for some reason, I think the dev environment doesn't have enough resources to run tests reliably

Update v5p cluster

---

dags/sparsity_diffusion_devx/jax_stable_stack_tpu_e2e.py

- Removing Axlearn<>JStS multi-slice test config.
- Changing the way in which we generate output_dir for maxdiffusion to avoid checkpoint conflict.
Verified changes are applied on an internal cluster.

Fixing broken tests

---

.gitignore
dags/multipod/maxtext_checkpointing.py
dags/multipod/maxtext_configs_aot.py
dags/multipod/maxtext_profiling.py
dags/multipod/maxtext_profiling_vertex_ai_tensorboard.py
dags/multipod/maxtext_trillium_configs_perf.py
dags/multipod/mxla_collective_nightly.py
dags/multipod/mxla_gpt3_6b_nightly_gke.py
dags/multipod/mxla_maxtext_nightly_gke.py
dags/multipod/pytorch.py
dags/sparsity_diffusion_devx/jax_stable_stack_gpu_e2e.py
dags/sparsity_diffusion_devx/jax_stable_stack_tpu_e2e.py
dags/sparsity_diffusion_devx/maxdiffusion_e2e.py
dags/sparsity_diffusion_devx/project_bite_gpu_e2e.py
dags/sparsity_diffusion_devx/project_bite_tpu_e2e.py

Add mlscale_onduty tag to more Dags

---

dags/multipod/maxtext_end_to_end.py

Use HF_TOKEN for tpu e2e tests. 
Tested locally

Use HF_TOKEN for tests

---

dags/map_reproducibility/a3ultra_llama_3_1_70b_nemo.py
dags/map_reproducibility/a3ultra_mixtral_8_7b_nemo.py
dags/map_reproducibility/utils/common_utils.py

Add Llama 3.1 aotc recipe regression test.
dev composer

Add Llama 3.1 aotc recipe regression test

---

dags/common/vm_resource.py

Updating tag as part of https://github.com/AI-Hypercomputer/maxtext/pull/1166
Verified changes locally.

Updating maxtext gpu image tag

---

dags/legacy_test/tests/pytorch/r2.6/common.libsonnet
dags/pytorch_xla/configs/pytorchxla_torchbench_config.py
dags/pytorch_xla/r2_6.py

Now that we produced the rc5 wheel and docker (https://github.com/pytorch/xla/runs/35622507657), update test to test that.
Staging: http://shortn/_UD3v9Bph1H

Update PyTorch/XLA 2.6 rc wheel to rc5

---

dags/common/vm_resource.py
dags/inference/trt_llm_inference.py
dags/inference/trt_llm_mlperf_v40_inference.py
dags/inference/trt_llm_mlperf_v41_inference.py
dags/pytorch_xla/pytorchxla-torchbench-release.py
dags/pytorch_xla/pytorchxla2_torchbench.py
dags/pytorch_xla/pytorchxla_torchbench.py
dags/solutions_team/solutionsteam_vllm_benchmarks.py

The old GPU image was retired
**Instruction and/or command lines to reproduce your tests:** 1. Establish a composer environment 2. Upload local change to GCS 3. Manually trigger DAG. 
**List links for your tests (use go/shortn-gen for any internal link):** https://pantheon.corp.google.com/composer/dags/us-central1/dyli/solutionsteam_vllm_benchmark/runs?e=13803378&inv=1&invt=Abm5Jw&mods=allow_workbench_image_override&project=cloud-ml-auto-solutions

Update GPU image

---

dags/legacy_test/tests/pytorch/r2.6/common.libsonnet
dags/pytorch_xla/configs/pytorchxla_torchbench_config.py

Update the CI to test rc6 instead of rc5.

Test PyTorch/XLA 2.6 rc6 wheel/docker

---

dags/multipod/maxtext_end_to_end.py

Fixing HF_TOKEN export in run_cmds. 
tested llama2-7b https://screenshot.googleplex.com/8PdChKdgtZpsQzV

fix HF_TOKEN export

---

dags/map_reproducibility/a3mega_llama_3_1_70b_nemo.py
dags/map_reproducibility/a3mega_llama_3_70b_nemo.py
dags/map_reproducibility/a3mega_mixtral_8_7b_nemo.py

Add all a3mega recipes regression tests

Add all a3mega recipes regression tests

---

dags/common/test_owner.py
dags/sparsity_diffusion_devx/maxtext_moe_gpu_e2e.py

Add a dag for MoE GPU E2E tests
Currently contains tests on A3 cluster using Maxtext pinned image
http://shortn/_fzy6Axeqjr
http://shortn/_TcxwEo9WRA

Add a dag for MoE GPU E2E tests

---

dags/mantaray/run_mantaray_jobs.py

rename run_workload with name

---

dags/solutions_team/solutionsteam_tf_nightly_supported.py

Our team is observing sporadic test failures during 6:50AM UTC and 7:00AM UTC (b/390638318). This PR updates the nightly test schedule to 8AM UTC instead. 

Update test schedule

---

dags/multipod/maxtext_gpu_end_to_end.py

Update scale_down_a3_cluster() in maxtext_gpu_end_to_end.py to configure project and cluster before scaling down the cluster. 
1. Run the following commands:
$ git clone -b yangyuwei-maxtext-gpu https://github.com/GoogleCloudPlatform/ml-auto-solutions.git
$ cd ml-auto-solutions/
$ bash scripts/upload-tests.sh gs://us-central1-nina-dags-fe347643-bucket/dags
2. Manually trigger `maxtext_gpu_end_to_end` DAG on the UI: https://540cef12d3da42ce97b48a97401b6c83-dot-us-central1.composer.googleusercontent.com/home
https://540cef12d3da42ce97b48a97401b6c83-dot-us-central1.composer.googleusercontent.com/dags/maxtext_gpu_end_to_end/grid?dag_run_id=manual__2025-01-16T23 …

Update scale_down_a3_cluster() in maxtext_gpu_end_to_end.py.

---

dags/common/quarantined_tests.py

Get the latest green tests out of "quarantine" bucket of `maxtext_gpu_end_to_end` DAG.
1. Run the following commands:
$ git clone -b yangyuwei-maxtext-gpu https://github.com/GoogleCloudPlatform/ml-auto-solutions.git
$ cd ml-auto-solutions/
$ bash scripts/upload-tests.sh gs://us-central1-nina-dags-fe347643-bucket/dags
2. Manually trigger maxtext_gpu_end_to_end DAG on the UI: https://540cef12d3da42ce97b48a97401b6c83-dot-us-central1.composer.googleusercontent.com/home
https://540cef12d3da42ce97b48a97401b6c83-dot-us-central1.composer.googleusercontent.com/dags/maxtext_gpu_end_to_end/grid
- …

Update QuarantineTests for `maxtext_gpu_end_to_end` DAG.

---

dags/legacy_test/tests/pytorch/r2.6/common.libsonnet
dags/pytorch_xla/configs/pytorchxla_torchbench_config.py

Tests: parsed the DAG just fine: http://shortn/_SD9ITJdagn

[PyTorch/XLA] Test rc9 wheel

---

dags/pytorch_xla/configs/pytorchxla_torchbench_config.py

Fix torchbench dependency installation issue.
[run link](https://dade15488e304a7dadc2e167f18721ee-dot-us-central1.composer.googleusercontent.com/dags/pytorchxla-torchbench/grid?dag_run_id=manual__2025-01-26T23%3A13%3A20.916109%2B00%3A00&tab=logs&task_id=torchbench_BERT_pytorch-v5litepod-4.run_model)

fix torchbench

---

dags/legacy_test/tests/pytorch/r2.6/common.libsonnet
dags/pytorch_xla/configs/pytorchxla_torchbench_config.py

Test PyTorch/XLA 2.6 rc10
http://shortn/_mc7rADKhww

Test rc10 wheel

---

dags/map_reproducibility/utils/common_utils.py

Updated helm install command to use clusterName to address incorrect network name when not provided. 
- [] I have run one-shot tests and provided workload links above if applicable.

Updated helm installed command to set clusterName.

---

dags/legacy_test/tests/pytorch/nightly/common.libsonnet
dags/legacy_test/tests/pytorch/r2.6/common.libsonnet

Follow up https://github.com/GoogleCloudPlatform/ml-auto-solutions/pull/578
Previous setup failing passed this time.
[internal link](https://efdb2a1d6c2c435b8b7de77690c286a9-dot-us-central1.composer.googleusercontent.com/dags/pytorchxla-r2-6/grid?tab=graph&task_id=pt-2-6-resnet50-pjrt-fake-v4-32-1vm&dag_run_id=manual__2025-01-25T01%3A07%3A57.254639%2B00%3A00)

fix lock issue

---

dags/legacy_test/tests/pytorch/r2.6/common.libsonnet
dags/pytorch_xla/configs/pytorchxla_torchbench_config.py

Test PyTorch/XLA final 2.6.0 wheel
http://shortn/_Pcmn7Hi3iM

Test final 2.6.0 wheel

---

dags/common/quarantined_tests.py

Move MoE TPU tests out of Quarantine due to the test greenness. 
Upload to airflow and see.
* Before the change - [link](https://screenshot.googleplex.com/4SYoMtZKjNfKebZ)
* After the change - [link](https://screenshot.googleplex.com/7J3LGfUJVaRx5Vx)

Move MoE TPU tests out of Quarantine

---

dags/common/model_configs.py
dags/multipod/maxtext_trillium_configs_perf.py
dags/multipod/maxtext_v5e_configs_perf.py

Update trillium and v5e perf model configs and update test scripts to use benchmark_runner.py
Ran a subset of the tests for each dag:
- maxtext_v5e_configs_perf- https://screenshot.googleplex.com/7fYF7UxxvFfuZSK
- maxtext_trillium_configs_perf.py- https://screenshot.googleplex.com/AEFbcoxCL363u5c

Update trillium and v5e perf tests

---

dags/common/quarantined_tests.py

Move maxdiffusion xlml test out of quarantine & Moved JStS tpu_e2e test out of quarantine
Uploaded to airflow to see.
maxdiffusion xlml test:
Before: [link1](https://screenshot.googleplex.com/9LeBXmpocird7P4)
After: [link2](https://screenshot.googleplex.com/4w5ZdmAjWxhLUCQ)
JStS tpu_e2e test:
Before: [link1](https://screenshot.googleplex.com/8Wx2Hi7mtyi7NhQ)
After: [link2](https://screenshot.googleplex.com/Azuoa69SseLRnmr)

Moved maxdiffusion xlml test & JStS tests out of quarantine

---

dags/map_reproducibility/a3ultra_mixtral_8_7b_nemo.py
dags/map_reproducibility/utils/common_utils.py

This PR does:
1. Update the a3ultra cluster name.
2. Change gcs logs saving location
3. Update image

Change regression tests to match the updated recipe

---

dags/map_reproducibility/a3ultra_mixtral_8_7b_nemo.py
dags/map_reproducibility/utils/common_utils.py

Move a3u load to a working cluster

---

dags/map_reproducibility/a3ultra_llama_3_1_70b_nemo.py
dags/map_reproducibility/a3ultra_mixtral_8_7b_nemo.py
dags/map_reproducibility/utils/common_utils.py

Fix tests and add support for A3U Llama 70b nemo

Add support for non aotc Llama a3u nemo test

---

dags/map_reproducibility/a3mega_gpt3_175b_nemo.py
dags/map_reproducibility/a3mega_llama_3_1_70b_nemo.py
dags/map_reproducibility/a3mega_llama_3_70b_nemo.py
dags/map_reproducibility/a3mega_mixtral_8_7b_nemo.py
dags/map_reproducibility/a3ultra_llama_3_1_70b_nemo.py
dags/map_reproducibility/a3ultra_mixtral_8_7b_nemo.py
dags/map_reproducibility/utils/common_utils.py

This PR changes the way it calculates schedule. 
Frequency of tests are now changed to weekly. 

Change frequency of tests to Thursday from daily

---

dags/common/test_owner.py
dags/multipod/maxtext_multi_tier_checkpointing.py
xlml/apis/task.py
xlml/utils/xpk.py

Add Multi-tier Checkpointing DAG for enabling XLML end-to-end test.
http://shortn/_xmxU9nLGIR

Add Multi-tier Checkpointing DAG.

---

dags/solutions_team/configs/vllm/vllm_benchmark_config.py

collect TTFT and ITL after https://github.com/AI-Hypercomputer/inference-benchmark/pull/4

enable streaming request to collect TTFT and ITL

---

dags/map_reproducibility/a3mega_gpt3_175b_nemo.py
dags/map_reproducibility/a3mega_llama_3_1_70b_nemo.py
dags/map_reproducibility/a3mega_llama_3_70b_nemo.py
dags/map_reproducibility/a3mega_mixtral_8_7b_nemo.py
dags/map_reproducibility/a3ultra_llama_3_1_70b_nemo.py
dags/map_reproducibility/a3ultra_mixtral_8_7b_nemo.py
dags/map_reproducibility/utils/common_utils.py

Add kueue back and add more utils

---

dags/map_reproducibility/utils/common_utils.py

Use DLSL image and change test times

---

dags/map_reproducibility/utils/common_utils.py

change dlsl image for mega

---

dags/map_reproducibility/a3mega_nemo_two_node.py
dags/map_reproducibility/a3ultra_nemo_two_node.py
dags/map_reproducibility/utils/common_utils.py

Add two node tests to run daily for a3mega and a3ultra

Add two node tests to run daily for both a3mega and ultra

---

dags/map_reproducibility/a3mega_nemo_two_node.py
dags/map_reproducibility/utils/common_utils.py

Add two node nemo test

---

dags/map_reproducibility/utils/common_utils.py

change cluster name

---

dags/map_reproducibility/a3mega/gpt3_175b_nemo.py
dags/map_reproducibility/a3mega/llama_3_1_70b_nemo.py
dags/map_reproducibility/a3mega/llama_3_70b_nemo.py
dags/map_reproducibility/a3mega/mixtral_8_7b_nemo.py
dags/map_reproducibility/a3mega/nemo_two_node.py
dags/map_reproducibility/a3ultra/llama_3_1_70b_nemo.py
dags/map_reproducibility/a3ultra/mixtral_8_7b_maxtext.py
dags/map_reproducibility/a3ultra/mixtral_8_7b_nemo.py
dags/map_reproducibility/a3ultra/nemo_two_node.py
dags/map_reproducibility/utils/common_utils.py

Maxtext a3ultra regression tests

Add Maxtext regression test for a3ultra mixtral

---

dags/map_reproducibility/a3mega/llama_3_1_70b_nemo.py
dags/map_reproducibility/a3ultra/llama_3_1_70b_maxtext.py
dags/map_reproducibility/a3ultra/llama_3_1_70b_nemo.py
dags/map_reproducibility/a3ultra/mixtral_8_7b_maxtext.py
dags/map_reproducibility/utils/common_utils.py

change model names to match bm db

---

dags/map_reproducibility/a3mega/llama_3_1_70b_nemo.py
dags/map_reproducibility/a3mega/llama_3_70b_nemo.py

change model names to match benchmark DB

---

.github/CODEOWNERS

add owner @Doris26 and @wang2yn84 to map_reproducibility

add owner to map_reproducibility

---

dags/legacy_test/tests/pytorch/nightly/common.libsonnet

Update torch_xla nightly wheel to 2.8.0

---

dags/legacy_test/tests/pytorch/r2.7/common.libsonnet
dags/pytorch_xla/configs/pytorchxla_torchbench_config.py
dags/pytorch_xla/r2_7.py

Update PTXLA test to rc3

---

dags/common/vm_resource.py

This PR updates v6e-256 cluster for Trillium Airflow tests.
Tested on local airflow server

Update v6e mlperf cluster

---

dags/legacy_test/tests/pytorch/r2.7/common.libsonnet
dags/pytorch_xla/configs/pytorchxla_torchbench_config.py

PyTorch/XLA 2.7-rc4 test

---

dags/map_reproducibility/internal_runs/a3ultra_maxtext_benchmarking_dags.py
dags/map_reproducibility/utils/common_utils.py
dags/map_reproducibility/utils/constants.py
dags/map_reproducibility/utils/internal_aotc_workload.py

add benchmark runs with stable-release image
graph: https://screenshot.googleplex.com/3haiPceupX4x4R9
dag run: https://screenshot.googleplex.com/89AET3UWC9Njc2E
- [X ] I have performed a self-review of my code.
- [ X] I have necessary comments in my code, particularly in hard-to-understand areas.
- [ X] I have run one-shot tests and provided workload links above if applicable. 
- [ X] I have made or will make corresponding changes to the doc if needed.

stable release runs

---

dags/sparsity_diffusion_devx/maxtext_moe_tpu_e2e.py

Upgrade to [TPU_V6E_256_MLPERF_CLUSTER](https://github.com/GoogleCloudPlatform/ml-auto-solutions/blob/2537d3bdd9a468b48226e412e8317292a106857a/dags/common/vm_resource.py#L262C2-L268)
b/407082730
Airflow test
http://shortn/_FXuecB8LuI

 Upgrade MoE TPU tests from v4 to v6e

---

dags/map_reproducibility/internal_runs/a3mega_maxtext_benchmarking_dags.py

Run not ready yet. Turn off
- [X ] I have necessary comments in my code, particularly in hard-to-understand areas.
- [X ] I have run one-shot tests and provided workload links above if applicable. 
- [X ] I have made or will make corresponding changes to the doc if needed.

turn off a3mega internal benchmarking

---

dags/map_reproducibility/utils/common_utils.py

mention namespace in pods cleanup

---

dags/map_reproducibility/internal_runs/a3ultra_maxtext_benchmarking_dags.py
dags/map_reproducibility/utils/common_utils.py
dags/map_reproducibility/utils/internal_aotc_workload.py

The original name logged into the metrics table is wrong. Get name from bash and report the correct name.
New name: https://screenshot.googleplex.com/6J2z7CekNm39ZwW
Metrics log as seen in this name: https://screenshot.googleplex.com/7jrPbhFvQuc5wbE

fix gcs bucket wrong name

---

dags/map_reproducibility/utils/common_utils.py

Change name in schedule and add remove maxtext two-node functionality

correct name in schedule for llama3-70b

---

dags/map_reproducibility/utils/internal_aotc_workload.py

Modify run_type to seperate external and internal recipe run
- [X ] I have performed a self-review of my code.
- [X ] I have necessary comments in my code, particularly in hard-to-understand areas.
- [X ] I have run one-shot tests and provided workload links above if applicable. 
- [X ] I have made or will make corresponding changes to the doc if needed.

modify run type for internal benchmarking

---

xlml/apis/task.py
xlml/utils/xpk.py

Add option to provide custom XPK branch. 
* Currently, XPK new version release interval is 2-3 weeks, it causes a long turn around period.

Add option to provide custom XPK branch

---

dags/map_reproducibility/utils/common_utils.py

update num_gpus in case of two node recipes

---

dags/legacy_test/tests/pytorch/r2.7/common.libsonnet
dags/pytorch_xla/configs/pytorchxla_torchbench_config.py

Enable r2.7 rc5 test
[link](https://dade15488e304a7dadc2e167f18721ee-dot-us-central1.composer.googleusercontent.com/dags/pytorchxla-r2-7/grid)

enable rc5 test

---

dags/map_reproducibility/utils/common_utils.py

update test db only when test env

---

.github/requirements.txt

Pin apache-airflow version

---

xlml/utils/xpk.py

Setting branch to 0.4.1 till the dependency issue is resolved.

Setting branch to v0.4.1 till the dependency issue is resolved.

---

dags/map_reproducibility/internal_runs/sample_a3ultra_maxtext_single_run.py
dags/map_reproducibility/utils/common_utils.py
dags/map_reproducibility/utils/internal_aotc_workload.py
dags/map_reproducibility/utils/sample_workload_utils.py

Add sample a3ultra benchmarking run entry
How to use: WIP
sample run local prints: https://paste.googleplex.com/6396862602674176
User Manual: https://docs.google.com/document/d/1hBMgXc44p69k2QLt2XALLTlsuyFcomJc8cpzs38zHwk/edit?tab=t.9f3f18vgln5o#bookmark=kix.pnvoy231zvpw
tested dag still work: https://screenshot.googleplex.com/LCTecKntuFASwp9

benchmark sample run

---

dags/multipod/maxtext_trillium_configs_perf.py
dags/multipod/maxtext_v5e_configs_perf.py

Update scripts in these perf tests to properly invoke maxtext training
Ran a test model in development Airflow env https://screenshot.googleplex.com/9z2fByn5Rv6dSw3

Fix v5e and v6e perf test script

---

dags/map_reproducibility/utils/common_utils.py
dags/map_reproducibility/utils/internal_aotc_workload.py
dags/map_reproducibility/utils/sample_workload_utils.py

skip first and last in metrics calculation based on the workloads input config
sample run a3ultra_llama3.1-8b_8gpus_fp8_maxtext: https://paste.googleplex.com/4710461007986688
sample run a3ultra_mixtral-8x7b_8gpus_bf16_maxtext: https://paste.googleplex.com/6165287629750272
Without skipping:
mfu: 0.6596740934798161
step_time: 10.744356626272202
With skipping:
mfu: 0.6699308197225912
step_time: 1.301198072731495

skip first and last in metrics calculation

---

dags/map_reproducibility/utils/common_utils.py

remove unused arg from copying

---

dags/multipod/maxtext_multi_tier_p2_checkpointing.py

Update MTC Phase-2 e2e tests XPK branch to "main", as previous branch doesn't have mtc-enabled.

Update MTC Phase-2 e2e tests XPK branch to "main"

---

dags/gcs_bucket.py
dags/multipod/maxtext_multi_tier_p2_checkpointing.py

Add MTC bucket to multi-tier checkpointing p2 tests, for MTC cluster to have more control on the bucket.

Add MTC bucket to multi-tier checkpointing p2 tests

---

dags/map_reproducibility/internal_runs/a3mega_maxtext_benchmarking_dags.py
dags/map_reproducibility/internal_runs/a3ultra_maxtext_benchmarking_dags.py
dags/map_reproducibility/internal_runs/a4_maxtext_benchmarking_dags.py
dags/map_reproducibility/utils/common_utils.py
dags/map_reproducibility/utils/internal_aotc_workload.py
dags/map_reproducibility/utils/sample_workload_utils.py

1. add all config to job name for easy debugging
2. correct retries, 0 for runs exceeding 15mins and 2 for runs within 15 mins
3. log dag_id along with job name
https://screenshot.googleplex.com/7YRNAP7B5af4ib7

debug runs from unknown dag

---

dags/map_reproducibility/utils/common_utils.py

add more log for deletion issue debugging
https://screenshot.googleplex.com/9y3JQm77h5BgBoA

add more log for deletion issue debugging

---

dags/map_reproducibility/utils/common_utils.py

Return default if model's docker image is not there

---

dags/map_reproducibility/utils/common_utils.py

Remove returning none in getting docker image for mega

---

dags/multipod/maxtext_configs_aot.py
dags/multipod/maxtext_configs_aot_hybridsim.py

Fix AOT compile script based on maxtext module api change
Ran AOT command on local VM

Fix aot test scripts based on maxtext api change

---

dags/map_reproducibility/utils/common_utils.py

log skipping steps for profiler
correct name for sample to make sure helm job name is within 53 chars
First 6 steps should be skipped: https://screenshot.googleplex.com/BEN88MzdLqgWoPV

log steps and rename sample run

---

.github/requirements.txt
dags/map_reproducibility/internal_runs/a3mega_maxtext_inference_benchmarking_dags.py
dags/map_reproducibility/internal_runs/dag_configs_inference.py
dags/map_reproducibility/utils/common_utils_inference.py
dags/map_reproducibility/utils/internal_aotc_inference_workload.py

GPU Inference Regression on Helm 
https://screenshot.googleplex.com/8dHRaHbCRUj3WkN
https://screenshot.googleplex.com/Agv5LpXAkUJ8mGE

GPU Inference Regression on Helm 

---

dags/map_reproducibility/internal_runs/dag_configs.py
dags/map_reproducibility/internal_runs/sample_a4_nemo_single_run.py
dags/map_reproducibility/utils/common_utils.py
dags/map_reproducibility/utils/constants.py
dags/map_reproducibility/utils/internal_aotc_workload.py
dags/map_reproducibility/utils/sample_workload_utils.py

modify training steps to 15 steps to save resources
enable a4 sample run with metrics
samle a3ultra maxtext: https://paste.googleplex.com/6295662779695104
sample a4 maxtext run: https://paste.googleplex.com/4910027019911168
sample a4 nemo run log:  https://paste.googleplex.com/5602741478752256

a4 nemo sample run

---

dags/map_reproducibility/internal_runs/dag_configs.py
dags/map_reproducibility/internal_runs/sample_a3ultra_maxtext_single_run.py
dags/map_reproducibility/internal_runs/sample_a3ultra_nemo_single_run.py
dags/map_reproducibility/utils/common_utils.py
dags/map_reproducibility/utils/constants.py
dags/map_reproducibility/utils/internal_aotc_workload.py
dags/map_reproducibility/utils/sample_workload_utils.py

sample a3u nemo run using the new helm charts
maxtext run log: https://paste.googleplex.com/5821328348938240
nemo: https://paste.googleplex.com/5821328348938240
dag work: https://screenshot.googleplex.com/77UDbdEGm2Xpsuv

sample a3u nemo run

---

dags/map_reproducibility/utils/internal_aotc_inference_workload.py

https://screenshot.googleplex.com/6XBkJC3AiMzQmZr
https://screenshot.googleplex.com/3SuzUQF7LR32gMz

Fix the minor error for JAX GPU Automation 

---

dags/map_reproducibility/internal_runs/a3ultra_nemo_benchmarking_dags.py
dags/map_reproducibility/internal_runs/dag_configs.py
dags/map_reproducibility/internal_runs/sample_a3ultra_maxtext_single_run.py
dags/map_reproducibility/internal_runs/sample_a3ultra_nemo_single_run.py
dags/map_reproducibility/utils/constants.py
dags/map_reproducibility/utils/internal_aotc_workload.py
dags/map_reproducibility/utils/sample_workload_utils.py

new_internal_stable_release_a3ultra_llama3.1-8b_8gpus_bf16_nemo: https://screenshot.googleplex.com/6oox93CqntHBLvj
new_internal_a3ultra_llama3.1-8b_8gpus_fp8_maxtext: https://screenshot.googleplex.com/8YUsKwgNcTSnpMZ
new_internal_a3ultra_mixtral-8x7b_16gpus_bf16_maxtext: https://screenshot.googleplex.com/59vQEppBybGCJZD
new_internal_stable_release_a3ultra_llama3.1-8b_8gpus_fp8_nemo: https://paste.googleplex.com/6439543794040832

a3ultra new dag using unite helm

---

dags/map_reproducibility/internal_runs/a3ultra_nemo_benchmarking_dags.py

fix schedule wrong naming
https://screenshot.googleplex.com/6WdT9G6doyWTpT8

fix schedule naming

---

dags/map_reproducibility/utils/common_utils_inference.py

https://screenshot.googleplex.com/7PyWMb4wEqf7DUD

Add date to Maxtext GPU Schema

---

dags/framework3p/microbenchmarks_dag.py

Update timeouts for microbenchmarks

update timeouts for microbenchmarks

---

dags/map_reproducibility/internal_runs/a3ultra_maxtext_benchmarking_dags.py
dags/map_reproducibility/internal_runs/sample_a3ultra_maxtext_single_run.py
dags/map_reproducibility/utils/common_utils.py
dags/map_reproducibility/utils/constants.py
dags/map_reproducibility/utils/internal_aotc_workload.py
dags/map_reproducibility/utils/sample_workload_utils.py

add maxtext nightly launcher
local run: https://paste.googleplex.com/4987689172205568
nemo: https://screenshot.googleplex.com/ApQ3LeEjwGfPKkC
maxtext: https://screenshot.googleplex.com/AeRZEzohqfEHGBq

add maxtext nightly launcher

---

dags/multipod/maxtext_trillium_configs_perf.py

Background: profile extraction (#728 + #744) is merged, stable on `prod`
- https://screenshot.googleplex.com/6ahhHenjsZZkWxk
- https://screenshot.googleplex.com/8nocAeJDncczBQT
Change: in the [trillium perf DAG](http://shortn/_OFhjMgl4Du), I am adding this feature for MoE tests: 
https://github.com/GoogleCloudPlatform/ml-auto-solutions/blob/ded4999006d94a230ee9107b460a7d4a58e8b67a/dags/common/model_configs.py#L37-L40
- the base command set `step=15` for train
- profile setting: default 
- benchmark_runner on device [uses workconfig](https://github.com/AI-Hypercomputer/maxtext/blob/fefce810f5d757f2123b84e4d5fba95cba67dbdc/benchmarks/benchmark_runner.py#L308) whose base_config is [default to base.yml](https://github.com/AI-Hypercomputer/maxtext/blob/fefce810f5d757f2123b84e4d5fba95cba67dbdc/b …

trillium perf moe tests: use profile

---

dags/multipod/maxtext_end_to_end.py

Move tests to v5p cluster until we find a resolution for b/422258996
N/A 

[MaxText] Move maxtext_end_to_end tests to v5p cluster

---

dags/map_reproducibility/utils/common_utils.py

fix Maxtext metrics calculation
sample run test: https://screenshot.googleplex.com/6pXmHAQYQwMMxYx
why we need additional one skip: https://screenshot.googleplex.com/6nZkbwSF2bMP98a

fix Maxtext metrics calculation

---

dags/common/vm_resource.py
dags/multipod/mxla_maxtext_nightly_gke.py

Adding v6e cluster for mxla maxtext nightly

v6e mxla nightly runs

---

dags/legacy_test/tests/pytorch/r2.8/common.libsonnet

Seeing errors from airflow given that the image trying to be fetched does not exist

Update rc for pytorchxla 2.8

---

dags/sparsity_diffusion_devx/maxdiffusion_tpu_e2e.py

Fix maxdiffusion test

---

.github/CODEOWNERS

Add code owner for orbax and tpu_observability
N/A

Add owners for orbax and tpu_observability

---

plugins/README.md
plugins/on_failure_actions.py
scripts/upload-tests.sh

Use github app authentication to replace personal access token. Update readme.md.
Fix error.

Fix alert plugin error. Migrate to GitHub App authentication.

---

dags/common/test_owner.py
dags/multipod/maxtext_configs_aot.py

The cluster for AOT test is outdated. We update it with a new cluster.

Update the GPU cluster in AOT test

---

dags/sparsity_diffusion_devx/jax_ai_image_gpu_e2e.py
dags/sparsity_diffusion_devx/jax_ai_image_tpu_e2e.py

Did not update DAG id in refactoring PR. Updating it in this PR. Naming change is from jax_stable_stack_* -> jax_ai_image_*

Updated DAG name to JAX AI Image

---

dags/multipod/legacy.py
dags/multipod/maxtext_checkpointing.py

* Move checkpoint resharding test from Legacy DAG to Checkpointing DAG
Tested on local airflow server and tests are passing

Move checkpoint resharding test to checkpointing DAG

---

dags/tpu_observability/multi_host_nodepool_rollback_dag.py

Fix tag in multi_host_nodepool_rollback_dag.py under project TPU-Observability.

Correct tags for all DAGs in TPU-Observability

---

dags/dashboard/xlml_to_buganizer.py

A DAG that periodically queries the status of GKE clusters to monitor their health, and writes the collected data as rows into the target Google Sheet.
Manual test.

add xlml_to_buganizer_dag

---

dags/dashboard/xlml_to_buganizer.py

Some status shouldn't be seem as error and create a ticket. Therefore, I add the specific status to prevent it.
manual test

Update xlml_buganizer.py to exclude provisioning status of a cluster or nodepool

---

dags/dashboard/airflow_to_bq_export.py

Update the schedule time of this dag to 1 am UTC.

update the schedule time of airflow_to_bq_export.py to 1 am

---

dags/orbax/maxtext_emc_restore_local.py
dags/orbax/maxtext_emc_save_gcs.py
dags/orbax/maxtext_mtc_emergency_save_local.py
dags/orbax/maxtext_mtc_save_gcs.py
dags/orbax/util/checkpoint_util.py
dags/orbax/util/test_config_util.py
dags/orbax/util/validation_util.py

This change adds a new DAG which test and verifies the Orbax Emergency Checkpointer manager saving functionality of checkpoints to GCS bucket . It checks`checkpoint_steps` are  stored into GCS bucket. This DAG automate the installation of the mtc driver.,but requires an existing cluster and an GCS bucket with HNS enabled .
- Dag Name: `maxtext_emc_save_gcs`
- Airflow Test Results: https://00bd7f16ee7e45da99e04dee351b40d8-dot-us-east1.composer.googleusercontent.com/dags/maxtext_emc_save_gcs/grid
- GCP Composer name: `erniechang-test` (under GCP project: `cloud-ml-auto-solutions`)
- GCP Composer version: `2.13.1`
- Bucket Name: gs://mtc-automation-bucket

Add a new DAG that tests orbax emergency checkpointing manager saving feature to GCS Bucket feature.

---

dags/dashboard/xlml_to_buganizer.py

Fix to get location information from view rather than querying api
Manual tests

Fix xlml_to_buganizer.py cannot query two clusters with the same names in two locations
