- apis/task.py
- implementations/utils/bigquery.py
- implementations/utils/metric.py
Add failed and missed job status
* missed: issues related to initialization & QR to get the machine
* failed: issues during setup and run model process, including timeout in run model
Also:
* set `post_process` retry at 1 as we have TODO to `handle Airflow retry to avoid duplicate records in tables`
* add trigger rule for generate_process_id with all_done, so the post_process will always be triggered no matter the states of upstream tasks
Tested it on Airflow & check metrics in logs of process process
UI: [link](https://screenshot.googleplex.com/4hyZPJfumCn2bqY)
```
1) Set …
```
> Add failed and missed job status

- configs/xlml/jax/solutionsTeam_flax_latest_supported_config.py
- dags/xlml/solutionsTeam_flax_latest_supported.py
Update ViT v4-32 on Flax as an convergence test example in XL ML (similar to benchmark tests).
* Test: [Link](https://screenshot.googleplex.com/6AhSnwWBmpBL89K)
* Dataset: [Link](https://screenshot.googleplex.com/dsVFZn9SKS3g3Qg)
> Add ViT convergence test on Flax

- configs/xlml/jax/solutionsTeam_pax_latest_supported_config.py
Currently pax stable tests are [running fine](https://screenshot.googleplex.com/9AYsxQJCBydH6oL). A minor change to update test names with `stable` to be consistent with existing tests:
* Add pax version - stable
* Remove unexpected `_c4` 
Upload to Airflow and check names
Test [link](https://screenshot.googleplex.com/548BCegZbzLTYZy)
> Update pax test names

- apis/gcp_config.py
- configs/vm_resource.py
- configs/xlml/jax/solutionsteam_flax_latest_supported_config.py
- dags/xlml/solutionsteam_flax_latest_supported.py
- implementations/utils/metric.py
Enable Flax ResNet on v5e and v5p:
* Capacities for both v5e and v5p are in project `tpu-prod-env-automated`
* Currently I manually set up VPC peering and firewall rules to unblock PT test release, but we should do it in Terraform for management
Tests for v5e and v5p pass: [link](https://screenshot.googleplex.com/47dfSQJCw7Dbt4J)
> Enable Flax ResNet on v5e and v5p

- apis/gcp_config.py
- implementations/utils/metric.py
Add dataset project attribute, so customers are able to specify which project to store the data. By default, use datasets in `cloud-ml-auto-solutions`.
In v5 cases, both composer env and database are hosted in `cloud-ml-auto-solutions`, and machines are provisioned in project `tpu-prod-env-automated`. 
Upload to Airflow, and test.
Test: [link](https://screenshot.googleplex.com/55NvAYpBnHjF7CS).
> Add dataset project attribute

- deployment/cloud_composer_template.tf
Change-Id: I781a1cfdd73424febf0449d17a8c63e0317abbf8
Noticed the high usage of scheduler CPU in prod stage [~90%](https://screenshot.googleplex.com/B4QwkhunPj6L8NY), so scale it up to 2 from 1. Other metrics are fine so far.
* I need to add all workload configs; otherwise other values will be set to null instead of default (if I only indicate scheduler count).
* Also, noticed dev env created manually has diff settings. So this PR will also fix that.
Run terraform plan.
```
Terraform will perform the following actions:
~ resource "google_composer_environment" "example_environment" …
```
> Upscale scheduler

- apis/task.py
Change-Id: Ifb3c12232b0665ef6db7f6fbe25a7e16d4c6bb7d
Update retry numbers from 1 to 0 for tasks that only execute once.
* Retries=2 means it attempts 3 times in total
* Noticed it `retried once` for [post-process](https://screenshot.googleplex.com/6JRxsCs3pumxwUe)
N/A
N/A
> Update retry numbers

- configs/vm_resource.py
- configs/xlml/pax/solutionsteam_pax_supported_config.py
- dags/xlml/solutionsteam_flax_latest_supported.py
- dags/xlml/solutionsteam_pax_nightly_supported.py
Add v5litepod tests for Pax.
* Resources are in project `tpu-prod-env-automated`
Test: [link](https://screenshot.googleplex.com/9RuBPKXZvEGiy2T) - unfortunately, it's failing at `Could not find a version that satisfies the requirement flax (unavailable) (from praxis) (from versions: 0.1.0rc1,...` - same error as now
> Add v5e tests for Pax

- configs/xlml/tensorflow/common.py
- configs/xlml/tensorflow/solutionsteam_tf_nightly_supported_config.py
- dags/xlml/solutionsteam_tf_nightly_supported.py
Add TF Keras API tests:
* Add tests for v2-8, v5e-4, and v5p-8
* TF Pod tests are blocked by this [PR](https://github.com/GoogleCloudPlatform/ml-auto-solutions/pull/15)
* simplified old tests by removing unneeded scripts/commands (please review and see if I missed anything)
Some tests are passing and some of them are failed. Similar like existing tests, but not exactly the same. We could migrate tests first and then debug if don't notice the difference. 
Overal test: [link](https://screenshot.googleplex.com/BTCmjF8zYohKMYX) - passed tests are green
A …
> Add TF Keras API tests

- dags/xlml/solutionsteam_tf_nightly_supported.py
Currently, due to capacity issues, Keras tests are [failing](https://screenshot.googleplex.com/agB5vB3Q9ufFBJi) when running in parallel. Update keras test to run in sequential order in short-term fix. Will move it back when capacity is ready in projects (i.e. b/318440465 for v2, b/318855898 for v5e).
This change has been applied to [TF SE nightly Keras tests](https://github.com/GoogleCloudPlatform/ml-auto-solutions/pull/66).
Upload to Airflow, and check graph view.
Graph view is expected: [link](https://screenshot.googleplex.com/3iLfQVM3vhA4BVC).
Before submitting this PR, …
> Update keras test order

- configs/gcs_bucket.py
- configs/xlml/tensorflow/solutionsteam_tf_nightly_supported_config.py
- dags/xlml/solutionsteam_tf_se_nightly_supported.py
Add TF SE nightly DLRM test for v2 and v4 [source code](https://github.com/GoogleCloudPlatform/ml-testing-accelerators/blob/master/tests/tensorflow/nightly-se/tf-dlrm-criteo.libsonnet#L120-L123). All tests in old infra were failing and same for most tests in new infra. I suggest we migrate first and then debug further.
In old infra: 
* v4-8 are failed due to the hang and timeout - [link](https://screenshot.googleplex.com/JdL9KbdjrnFDjNG)
* v2-32 failed due to  `NotFoundError: Exception encountered when calling layer 'ranking' (type Ranking)` error - [link](https://screenshot.googleplex.com/8pTeHiL54fJx6Xv)
In new infra:
* v2-8 - pass
* v2-32 - failed due to `PermissionDeniedError: /tmp/output/train; Permission denied` error. I am not sure why this happen on v2-32 only.
* v4-8 - hang and …
> Add TF SE nightly DLRM test

- configs/xlml/jax/solutionsteam_flax_latest_supported_config.py
- dags/xlml/solutionsteam_flax_latest_supported.py
Add conv tests for BART and BERT:
* Create helpers for commonly used commands
* Add helper config `get_flax_bart_conv_config` for BART conv tests - [source](https://github.com/GoogleCloudPlatform/ml-testing-accelerators/blob/master/tests/jax/latest/flax-bart-wiki_summary.libsonnet)
* Add helper config `get_flax_bert_conv_config` for BERT conv tests - [source bert-mnli](https://github.com/GoogleCloudPlatform/ml-testing-accelerators/blob/master/tests/jax/latest/flax-bert-glue_mnli.libsonnet), [source bert-mrpc](https://github.com/GoogleCloudPlatform/ml-testing-accelerators/blob/master/tests/jax/latest/flax-bert-glue_mrpc.libsonnet)
* Other small changes, i.e. variable name change for ViT conv test
**Instruction and/or …
> Add conv tests for BART and BERT

- configs/maxtext/common.py
- configs/maxtext/maxtext_gce_config.py
- dags/maxtext/maxtext_nightly.py
Run maxtext nightly on 1 slice of v4-8
Test logs: https://screenshot.googleplex.com/KNCMu8sQyxeNXWs.png
Test result: https://screenshot.googleplex.com/7sXcqLTgiAKcXKc.png
> Add maxtext nightly test on 1 slice of v4-8

- dags/vm_resource.py
- xlml/utils/tpu.py
* Add valid_until_duration feature to QR
* Add available on-demand zones for resources based on b/318440465, b/318446082 
* Changes in QR: [link](https://screenshot.googleplex.com/5gNznsXPqyJKNB6)
* QR failed at the time, which is expected: [link](https://screenshot.googleplex.com/8fTAa7wW4qaQru3)
> Add valid_until_duration to QR

- dags/examples/maxtext_sweep_gce_example_dag.py
- dags/examples/maxtext_sweep_gke_example_dag.py
- dags/multipod/configs/maxtext_gce_config.py
- dags/multipod/configs/maxtext_sweep_gce_config.py
- dags/multipod/configs/maxtext_sweep_gke_config.py
- dags/multipod/maxtext_nightly.py
- dags/test_owner.py
- dags/vm_resource.py
- xlml/apis/task.py
- xlml/utils/xpk.py
Add configs/dags for launching parameter job sweeps with MaxText on GCE and GKE.
* `maxtext_sweep_gce_config` and `maxtext_sweep_gke_config` will take in test settings (project_name, tpu_type, num_slices, etc.) and maxtext sweep parameters (per_device_batch_size, remat_policy, ici_tensor_parallelism, etc.), generate all combinations of sweep parameter configurations, and then launch QR jobs or XPK workloads for all configurations
* `maxtext_sweep_gke_example_dag` and `maxtext_sweep_gce_example_dag` are example dags for using these configs
* Successfully ran `maxtext_sweep_gce_example_dag` which launched 3 MaxText QR jobs on 1xv4-8 varying the per_device_batch_size
* Successfully ran `maxtext_sweep_gke_example_dag` which launched 3 MaxText GKE/XPK workloads on 1xv4-128 varying the …
> Add MaxText parameter sweep configs/dags on GCE and GKE

- dags/pytorch_xla/pytorchxla_torchbench.py
- dags/vm_resource.py
1. Reduce V100/A100 GPU to use only 1 core to prevent running out of capacity
2. Update torchbench schedule to run everyday at 3:00AM PST.
> Update torchbench scheduler and reduce GPU core reservation

- dags/multipod/configs/common.py
- dags/multipod/configs/maxtext_gce_config.py
- dags/multipod/maxtext_end_to_end.py
- dags/multipod/maxtext_nightly.py
- dags/test_owner.py
Add decode test for Llama2, Mistral, and Gamma
* Reuse the end-to-end bash scripts in MaxText repo
* This PR needs to be done along with another PR in MaxText repo - [PR](https://github.com/google/maxtext/pull/379)
Upload to Airflow, and test.
* Successful run for three models on both stable and nightly on Airflow: [link](https://screenshot.googleplex.com/3DBMBFEaMgXyz2A)
> Add MaxText tests for Llama2, Mistral, and Gamma

- dags/examples/maxtext_nightly_with_startup_script_example.py
- dags/multipod/configs/common.py
- dags/multipod/configs/maxtext_gce_config.py
- dags/multipod/maxtext_end_to_end.py
- dags/multipod/maxtext_nightly.py
Update the maxtext nightly test to:
* Apply the newest network settings by `bash preflight.sh PLATFORM=gce/gke` in `set_up_cmds`
* Add `automated_test` into [dags/multipod/maxtext_nightly.py](https://github.com/GoogleCloudPlatform/ml-auto-solutions/commit/9f8e463931b2d714ca278de04906a09990de7f9f#diff-232f309a139b0185a56ea735057e9156f8cd12d54f3f88bab53480c6b77a78f2) to identify manual/automated test.
* Update the maxtext-nightly output folder based on MXLA team's request.
Upload to Airflow, and test.
https://screenshot.googleplex.com/8dwcKppQiNvncD8 …
> Update the maxtext nightly test 

- deployment/cloud_composer_template.tf
Scale up the env, as more tests are onboarding (noticed a few tasked being killed and waiting in queue):
* change env size from small to medium, so it allows more total dags and running tasks - [ref](https://screenshot.googleplex.com/BpCfDLtfzNk3Q9X)
* increase the max number of workers from 3 to 100, so the env can automatically scale up when needed
* increase `scheduler-min_file_process_interval` from default 30s to 120s, and increase the scheduler to 4 to address [long duration of parse time of dags](https://screenshot.googleplex.com/7MTYTizxRk45b5y). In tutorial it mentioned `The default DAG parsing frequency in Airflow is 30 seconds; if DAG parsing time exceeds this threshold, parsing cycles start to overlap, which then exhausts scheduler's capacity.` 
Please describe the tests that …
> Scale up the env

- deployment/cloud_composer_template.tf
Add compute.instanceAdmin.v1 role to PROD and DEV environment. The role is for creating VM instance through gcp v1 api.
> add compute instance admin role

- deployment/cloud_composer_template.tf
After the deployment of [change](https://github.com/GoogleCloudPlatform/ml-auto-solutions/pull/101), I still noticed [tasks being killed](https://screenshot.googleplex.com/8Na9jzngtnLcDeH). 
Based on tutorial: `The most common reason for Zombie tasks is the shortage of CPU and memory resources in your environment's cluster. As a result, an Airflow worker might not be able to report the status of a task, or a sensor might be interrupted abruptly. In this case, the scheduler marks a given task as a Zombie task. To avoid Zombie tasks, assign more resources to your environment.`
* Update worker memory_gb from 8 to 13, and increase worker CPU from 2 to 8
For scheduler, I noticed this recommendation from [UI](https://screenshot.googleplex.com/7Lh9K3pqH8XES7f):
* reduce number of schedulers from …
> Update CPU and memory for cluster

- xlml/utils/xpk.py
Fix gcloud cli install for XPK docker images and increase KubernetesPodOperator ephemeral-storage.
* update `google-cloud-sdk` install to `google-cloud-cli` install due to b/324101663
* update `google-cloud-cli` installation to follow steps from [here](https://cloud.google.com/sdk/docs/install#deb)
* increase `ephemeral-storage` for `KubernetesPodOperator`- was seeing errors like https://screenshot.googleplex.com/8SqhcKuZFMG4wZD when trying to install packages on the docker image
* ran `maxtext-sweep-gke-example-dag` http://shortn/_Z7TfN6Lem8
> Fix gcloud cli install and increase KubernetesPodOperator ephemeral-storage

- dags/solutions_team/configs/tensorflow/solutionsteam_tf_nightly_supported_config.py
DLRM nightly tests are failing due to an unrecognized keras optimizer. Setting the legacy keras flag (already present on the [other tests](https://github.com/GoogleCloudPlatform/ml-auto-solutions/blob/62a169c4ce3ebc4bd297cd3f0ea2f91d5f70c274/dags/solutions_team/configs/tensorflow/solutionsteam_tf_nightly_supported_config.py#L60))
I ran the DLRM test locally with the flag and it passed as expected. Changing nothing except unsetting that flag resulted in the same failure that they nightly tests are seeing.
- [ X ] I have run one-shot tests and provided workload links above if …
> Adding TF_USE_LEGACY_KERAS flag to DLRM runs

- .gitignore
- README.md
- docs/contributing.md
See README diff
Tested instructions locally with a WIP DAG.
> Add instructions to run a local Airflow server

- dags/multipod/configs/maxtext_sweep_gce_config.py
- dags/multipod/configs/maxtext_sweep_gke_config.py
- xlml/utils/metric.py
- xlml/utils/metric_test.py
* Add `metric_aggregation_strategy` to metadata during metrics post processing
* Allow aggregation strategy to be configured from DAG in `maxtext_sweep_gce_config` and `maxtext_sweep_gke_config`
* Add type annotation for `sweep_params`
* Ran `maxtext_sweep_gke_example_dag` in local dev composer environment http://shortn/_0gmUFPCfcH
> Add metric_aggregation_strategy to metadata

- dags/solutions_team/configs/tensorflow/common.py
- dags/solutions_team/configs/tensorflow/solutionsteam_tf_2_16_supported_config.py
- dags/solutions_team/solutionsteam_tf_2_16_se_supported.py
- dags/solutions_team/solutionsteam_tf_2_16_supported.py
- dags/vm_resource.py
Adds two new DAGs to test TF against the 2.16 release candidate.
Tests still pending, getting the code change in PR in the meantime and will test before merging.
**Instruction and/or command lines to reproduce your tests:** TK
**List links for your tests (use go/shortn-gen for any internal link):** TK
> Adding new DAGs for TF 2.16 release tests

- dags/pytorch_xla/configs/pytorchxla_torchbench_config.py
- dags/pytorch_xla/pytorchxla_torchbench.py
- xlml/apis/metric_config.py
- xlml/apis/task.py
- xlml/utils/gpu.py
- xlml/utils/metric.py
- xlml/utils/name_format.py
- xlml/utils/tpu.py
1. Support env to runner to dynamic change run command
2. Support passing gs file location to `run_model` and `post_process` function
3. update `provision` phase to generate gcs file based on current timestamp.
Note:
You need to to set `MetricConfig.use_runtime_generated_filename=True` to tell post_process to use process generated filename.
torchbench: [run](https://08398f98ca104983a06a424b851a390d-dot-us-central1.composer.googleusercontent.com/dags/pytorchxla-torchbench/grid)
Other's test like maxtext: [run](https://08398f98ca104983a06a424b851a390d-dot-us-central1.composer.googleusercontent.com/dags/maxtext_nightly/grid?dag_run_id=manual__2024-02-22T03%3A03%3A45.831358%2B00%3A00)
Flax [run](https://08398f98ca104983a06a424b851a390d-dot-us-central1.composer.googleusercontent.com/dags/flax_l …
> support env to runner to dynamic change run command

- dags/solutions_team/configs/tensorflow/common.py
- dags/solutions_team/solutionsteam_tf_2_16_se_supported.py
- dags/solutions_team/solutionsteam_tf_2_16_supported.py
* Modifies the schedule of TF 2.16 release tests to only run on-demand
* Fixes a bug in the setup relating to the tf 2.16 pip install
* Note: another bug remains in the tf 2.16 resnet setup that I will fix in a future changeset
Ran a sample tf-keras test: http://shortn/_kCMq0Dcs80
> Set TF 2.16 tests to run on-demand and fixed a bug in the setup script

- dags/multipod/configs/maxtext_gce_config.py
- dags/multipod/mxla_maxtext_nightly.py
1. Add `ENABLE_PJRT_COMPATIBILITY=true` to relax the libtpu/jaxlib version check for nightly test.
2. Also rename the test name from `maxtext_nightly` to `mxla_maxtext_nightly`.
Tested on Airflow.
https://screenshot.googleplex.com/7fwW6T5DiUz5LeQ
> Add `ENABLE_PJRT_COMPATIBILITY=true` and rename `maxtext_nightly`

- dags/legacy_test/tests/pytorch/nightly/resnet50-mp.libsonnet
- dags/pytorch_xla/nightly.py
Use fake data for ResNet50 SPMD test. `imagenet-mini` is not available in the test environment.
n/a
> Switch ResNet50 SPMD test to use fake data

- dags/solutions_team/configs/tensorflow/solutionsteam_tf_2_16_supported_config.py
Adds a missing WRAPT_DISABLE_EXTENSIONS=true environment flag.
Consolidates TF_USE_LEGACY_KERAS=1 into a single location.
Ran 2.16 tests on Resnet and DLRM which were previously failing and are now passing.
Ran 2.16 test on tf-keras which remains passing.
**List links for your tests (use go/shortn-gen for any internal link):**/
[tf-keras](http://shortn/_qsMrqm5hQr)
[Resnet](http://shortn/_Uu4K6ZCxbt)
[DLRM](http://shortn/_nGYQPWVVus)
- [ X ] I have made or will make corresponding changes to the doc …
> Adds missing WRAPT_DISABLE_EXTENSIONS=true flag

- dags/pytorch_xla/nightly.py
The name prefix breaks post process, e.g.
```
File "/home/airflow/gcs/dags/xlml/utils/metric.py", line 671, in process_metrics
test_job_status = get_gce_job_status(task_test_config, use_startup_script)
...
airflow.exceptions.TaskNotFound: Task pt-nightly-llama2-pjrt-infer-func-v4-8-1vm-1vm.provision.create_queued_resource.wait_for_ready_queued_resource not found
```
The prefix isn't useful. We just want to group tests by topic in the Airflow UI.
n/a, reverts tests to old IDs
> [PT/XLA] Remove task group prefix from PyTorch nightly test groups.

- dags/legacy_test/tests/pytorch/nightly/llama2-model.libsonnet
Quick fix to fix llama2 dynamo script.
dynamo can't be set to True in the testing script:
```
python3 llama/example_text_completion.py True "/home/xl-ml-test/llama/7B" /home/xl-ml-test/spiece.model --max--max_gen_len=1000 --max_batch_size=2 --dynamo=True
```
Need to specify either openxla or openxla_eval.
> fix llama dynamo

- dags/legacy_test/tests/pytorch/nightly/hf-bert.libsonnet
Fixes `ImportError: To be able to use evaluate-metric/accuracy, you need to install the following dependencies['scikit-learn'] using 'pip install sklearn' for instance'`
Tested locally on a TPU v4.
> [PT/XLA] Add `scikit-learn` to BERT test config

- deployment/cloud_composer_template.tf
With larger tests, schedulers are near the maximum utilization:
This may be causing an increase in zombies and interrupted tasks:
See https://cloud.google.com/composer/docs/how-to/using/troubleshooting-dags#zombie-tasks
n/a
> Increase size of schedulers

- scripts/upload-tests.sh
Update sync up algorithm to use checksum, instead of mtime.
```
-c 
Causes the rsync command to compute and compare checksums (instead of comparing mtime)
for files if the size of source and destination match. This option increases local disk I/O and run 
time if either src_url or dst_url are on the local file system.
```
Test it in build.
* 1st build: upload 29 files - [link](https://screenshot.googleplex.com/3mzQ9r8yMDLYRMj)
* 2nd build: upload 0 file - [link](https://screenshot.googleplex.com/AeAQLB4YDA3qhSm)
Before submitting this PR, please make sure (put X in square …
> Update sync up algorithm

- dags/pytorch_xla/nightly.py
- xlml/apis/test_config.py
We have more on-demand capacity for v4 than reserved. Also switching JAX tests to on-demand since they're low priority.
n/a
> [PT/XLA] Use on-demand capacity for v4 tests

- dags/legacy_test/tests/pytorch/nightly/ci.libsonnet
Fixes `ModuleNotFoundError: No module named 'expecttest'`
> [PT/XLA] Install expecttest in CI test script

- dags/pytorch_xla/configs/pytorchxla_torchbench_config.py
Torchbench always check the token if we import models from hugging face: https://github.com/pytorch/benchmark/blob/8ffe57ecb5df6af5c458684f1834fbe78adfda00/torchbenchmark/util/framework/huggingface/model_factory.py#L191-L195. The token is not a must for public models. We use fake token to bypass torchbench HF init check.
Details: https://b.corp.google.com/issues/324078896#comment6.
> Use fake token to bypass torchbench HF init check

- .github/requirements.txt
- dags/examples/xpk_example_dag.py
- deployment/cloud_composer_template.tf
- docs/contributing.md
- scripts/local-airflow.sh
- xlml/apis/task.py
- xlml/utils/xpk.py
Enable running XPK using a local Airflow environment, and integrate the `run_workload` using Taskflow. The task type should be conditionally determined by the execution environment: local Airflow tasks should use `task.docker`, and in the Composer environment `task.kubernetes` should be used.
*Note that the VM hosting the standalone Airflow server must have sufficient permissions to create workloads in the target GKE cluster.*
This change also adds a couple of ease-of-use enhancements for standalone runs:
- Disable login for the local server, and run on localhost
- Remove example DAGs to only show the desired one.
- Ran example_gke_dag locally (1-slice failed due to VM permission issues, 2-slice started): http://screen/Aj5fJLtzuiCi9Dk
- Ran example_gke_dag in a Composer environment …
> Allow running xpk workloads with standalone Airflow

- dags/multipod/configs/gke_config.py
- dags/multipod/maxtext_configs_aot.py
- dags/multipod/maxtext_convergence.py
- dags/vm_resource.py
Adding nightly AOT compilation GKE tests for MaxText configs running on `v4-8-maxtext` cluster. Runs AOT scripts for all configs found in `v4`, `v5e`, and `v5p` directories in https://github.com/google/maxtext/tree/main/MaxText/configs
Ran in local composer environment http://shortn/_6NgKh4BaUn. There is a failure with the 128B config on v5e-256 due to a compiler bug being tracked in b/327447977. This failure is unrelated to the set up of the nightly testing in XLML.
> Add nightly AOT compilation GKE tests for MaxText configs

- dags/legacy_test/tests/pytorch/nightly/common.libsonnet
In b/329297378 and b/329295948, we have seen an error:
```
[2024-03-11, 14:06:30 UTC] {gke.py:116} INFO - pt-nightly-resnet50-mp-fake-v100-x2x2-9jhn2-1-6x5j8] --2024-03-11 14:06:30--  https://github.com/pytorch/xla/archive/refs/heads/master.tar.gz
[2024-03-11, 14:06:50 UTC] {gke.py:116} INFO - pt-nightly-resnet50-mp-fake-v100-x2x2-9jhn2-1-6x5j8] Resolving github.com (github.com)... failed: Temporary failure in name resolution.
[2024-03-11, 14:06:50 UTC] {gke.py:116} INFO - pt-nightly-resnet50-mp-fake-v100-x2x2-9jhn2-1-6x5j8] wget: unable to resolve host address ‘github.com’
[2024-03-11, 14:06:50 UTC] {gke.py:116} INFO - pt-nightly-resnet50-mp-fake-v100-x2x2-9jhn2-1-6x5j8] gzip: stdin: unexpected end of file
[2024-03-11, 14:06:50 UTC] {gke.py:116} INFO - …
```
> Fix a flaky wget issue.

- dags/legacy_test/tests/pytorch/nightly/ci.libsonnet
Per the [log](https://46c56b977f2b44158661f1ef150119c7-dot-us-central1.composer.googleusercontent.com/log?dag_id=pytorchxla-nightly&task_id=pt-nightly-ci-func-v5litepod-4-1vm.run_model&execution_date=2024-03-12T14%3A00%3A00%2B00%3A00), the v5litepod CI is failing with error:
```
[2024-03-13, 15:13:27 UTC] {logging_mixin.py:150} WARNING - + python3 test/test_pallas.py
[2024-03-13, 15:13:30 UTC] {logging_mixin.py:150} WARNING - WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1710342810.006137  223407 pjrt_api.cc:100] GetPjrtApi was found for tpu at /home/ml-auto-solutions/.local/lib/python3.10/site-packages/torch_xla/lib/libtpu.so
I0000 00:00:1710342810.006186  223407 pjrt_api.cc:79] PJRT_Api is set for device type tpu
[2024-03-13, 15:13:30 …
```
> Fix v5litepod CI

- dags/multipod/maxtext_end_to_end.py
- xlml/utils/xpk.py
Migrate MaxText end_to_end tests to use XPK capacity. It also adds dependencies between the stable and nightly tests and ensures the generated name is valid for XPK workloads.
Ran in a cloud composer environment: https://fc137785b6c943a4af82d0671bf0ebe5-dot-us-central1.composer.googleusercontent.com/dags/maxtext_end_to_end/grid
Failures have been addressed in MaxText and will be picked up in tonight's docker image.
> Migrate MaxText end_to_end to xpk

- dags/multipod/configs/gke_config.py
- dags/multipod/configs/maxtext_sweep_gce_config.py
- dags/multipod/configs/maxtext_sweep_gke_config.py
- dags/multipod/maxtext_convergence.py
Add metric collection into BigQuery for maxtext convergence test. Will be able to store metrics like final loss.
This PR needs https://github.com/google/maxtext/pull/512 to be submitted first into maxtext to prevent run_name conflicts.
Ran maxtext_convergence test in local composer env http://shortn/_25kKsnd9y2 and was able to automatically collect metrics into BigQuery http://screen/8nLdcWaZAze5NC2.
> Add metric collection to maxtext convergence test

- dags/multipod/configs/legacy_unit_test.py
- dags/multipod/legacy.py
- dags/multipod/legacy_tests/gpt1-like.py
- scripts/dag-check.sh
- scripts/local-airflow.sh
- xlml/utils/xpk.py
The multipod team is migrating tests from the old XL ML test infrastructure. This change provides two example migrations:
- `gpt1-like` to demonstrate the process to migrate custom test scripts out of the old repository
- `maxtext-decode` to show how to migrate a MaxText end_to_end test.
The test scripts which were hosted in the old repository will be moved into the `dags/multipod/legacy_tests` folder.
These tests will run using XPK, and this change includes some minor related changes:
- Allow up to 20 hours for `wait_for_workload_completion`. Since XPK includes a scheduler through Kueue, we should allow tests to be queued up from Airflow and to run as capacity becomes available in the XPK cluster.
- Immediately terminate `wait_for_workload_completion` without retry if the workload pod …
> Example migration of Multipod XL ML test

- dags/solutions_team/configs/tensorflow/common.py
- dags/solutions_team/configs/tensorflow/solutionsteam_tf_nightly_supported_config.py
- dags/solutions_team/configs/tensorflow/solutionsteam_tf_release_supported_config.py
- dags/solutions_team/solutionsteam_tf_release_se_supported.py
- dags/solutions_team/solutionsteam_tf_release_supported.py
Refactors the release DAG to allow for easy swapping of versions for reuse in future releases and renames the modules to be more generic (`...tf_release...` instead of `...tf_2_16...`).
Also changes some typing references (e.g. `list` instead of `typing.List`) to adhere to Python best practices [PEP 585](https://peps.python.org/pep-0585/). This specific change will require python 3.11+ but adding `from __future__ import annotations` can allow python 3.7+. If we still need to support the older versions, I can update this change to include that.
Ran 2.16 release PJRT and SE keras tests, both were successful.
Variety of tests of both nightly and 2.15.1 DAGS as well as from resnet and tf-keras tests: …
> Refactored 2.16 release into a more reusable template

- dags/solutions_team/configs/tensorflow/common.py
Makes the repo cloning step more resilient in case the repo already exists.
I ran a keras test that was failing due to this issue and it is now passing that step.
http://shortn/_RBZjspOxFM
> Adding resiliency to the repo clone command

- dags/gcs_bucket.py
- dags/multipod/configs/gke_config.py
- dags/multipod/configs/maxtext_gce_config.py
- dags/multipod/configs/mxla_collective_config.py
- dags/multipod/maxtext_convergence.py
- dags/pytorch_xla/configs/pytorchxla_torchbench_config.py
- dags/solutions_team/configs/flax/solutionsteam_flax_latest_supported_config.py
- dags/solutions_team/solutionsteam_pax_latest_supported.py
- dags/solutions_team/solutionsteam_pax_nightly_supported.py
- xlml/apis/metric_config.py
- xlml/apis/task.py
- xlml/utils/metric.py
- xlml/utils/metric_test.py
- xlml/utils/name_format.py
Currently, we can generate a dedicated gcs folder for each test - [source](https://github.com/GoogleCloudPlatform/ml-auto-solutions/blob/067303ba64a25183ca7b592632c06507a10d1284/xlml/utils/name_format.py#L51), and this task is in provision in GCE track. 
We could have a separate PR to enable this for GKE track (xpk), so:
* we don't need to indicate `use_runtime_generated_gcs_folder` flag & base_output_directory
* all tests results are stored in dedicated folder based on benchmark ID.
Gradually, we want to reduce the gap between XLML functional tests and benchmarking tests. In this PR:
* Fix issue in TensorBoard summary processing
* Consolidate both func and benchmarking outputs into `output` folder
* Update Flax conv tests' GCS folder to use the default one.
Please describe the tests that …
> Generalize gcs location for tests

- dags/legacy_test/tests/pytorch/nightly/hf-diffusers.libsonnet
- dags/pytorch_xla/nightly.py
- dags/pytorch_xla/r2_3.py
Reenable diffuser tests with a new dataset
https://402f31b802dc42918d8712d630ea643a-dot-us-central1.composer.googleusercontent.com/dags/pytorchxla-nightly/grid?root=&dag_run_id=manual__2024-03-25T23%3A14%3A45.175887%2B00%3A00&tab=logs&task_id=pt-nightly-hf-diffusers-func-v4-8-1vm.run_model
> Reenable diffuser tests with a new dataset

- dags/examples/maxtext_aqtp_version_sweep_gke_example_dag.py
- dags/test_owner.py
- dags/vm_resource.py
As titled, added maxtext sweep example for AQTP library version compatibility test by following the gke sweeping api.
Scripts confirm performance remains consistent across versions. Will trigger this test ad-hoc upon library updates.
> Added maxtext sweep example for AQTP library version compatibility test

- dags/multipod/maxtext_configs_aot.py
- dags/multipod/maxtext_v5e_configs_perf.py
Adding a nightly test that runs 16B, 32B, 64B, 128B MaxText configs on 1, 2 x v5e-256 with nightly, stable jax and bf16, int8 quantization.
Ran in local environment http://shortn/_P9Dx85Ouf4. There is a failure for the 128B config on 2 slices due to a compiler bug being investigated separately.
> Add nightly MaxText perf tests on v5e

- dags/multipod/configs/pytorch_config.py
- dags/multipod/pytorch.py
- dags/vm_resource.py
Migrate multislice PyTorch tests to Airflow.
Also, add support for generated GCS paths in XPK. Unfortunately, task.docker and task.kubernetes execute in an isolated environment without any dependencies available, so we can't directly reference the `metric_config` module to retrieve the value. This requires hard-coding the GCS_OUTPUT environment variable's name into the XPK workload creation command.
Ran the tests locally (metrics failures are expected with local airflow): https://screenshot.googleplex.com/BGUoFgA7NBGZ9AA
> Migrate multislice PyTorch tests to Airflow

- xlml/utils/xpk.py
XPK introduced a change to avoid restarting the pod on usercode failure by default, which implies not propagating failure to the workload pods: https://github.com/google/xpk/pull/99
This has silently suppressed failures in the XL ML test grid, since the pod phase determines the success or failure of workloads (see http://shortn/_mxSv7puPQn)
Since max-restarts is [0](https://github.com/google/xpk/blob/main/xpk.py#L4908) by default, this flag won't actually trigger a rerun.
Ran locally, and the tests failed as they should: https://screenshot.googleplex.com/AoCubXY75NCVUa3
> Propagate XPK exit code to pod phase

- dags/solutions_team/configs/tensorflow/common.py
- dags/solutions_team/configs/tensorflow/solutionsteam_tf_nightly_supported_config.py
- dags/solutions_team/configs/tensorflow/solutionsteam_tf_release_supported_config.py
- dags/solutions_team/solutionsteam_tf_release_se_supported.py
- dags/solutions_team/solutionsteam_tf_se_nightly_supported.py
- dags/vm_resource.py
Adds a v5p-8 DLRM test
Also does some other minor housekeeping changes
Nightly tests are failing in the same way as they are currently: http://shortn/_NvBaOUspmv http://shortn/_XR5kKdSdKn http://shortn/_fVMe30WNnY
Keras on tf 2.15: http://shortn/_Vgcnd0vVMQ
Keras + Resnet on tf se 2.15: http://shortn/_Nfb9IA09Xs http://shortn/_UsYbrGAtmw
DLRM v5p (second run shows clearing the directory for checkpointing):  http://shortn/_YlWBZUs47B http://shortn/_jn8lFG3GPv
DLRM v5p with the checkpoint path change: http://shortn/_FAJPUle0QF
> Adds a DLRM Tensorflow test that runs on a v5p-8

- dags/multipod/configs/gke_config.py
- dags/multipod/maxtext_end_to_end.py
Add 1vm.sh and 2vm.sh for llama 7b gpu training
Manually tested on Airflow
https://540cef12d3da42ce97b48a97401b6c83-dot-us-central1.composer.googleusercontent.com/dags/maxtext_end_to_end/grid?dag_run_id=manual__2024-04-12T13%3A32%3A50.088355%2B00%3A00&tab=graph
> Add 1vm and 2vm llama 7b gpu training

- dags/legacy_test/tests/pytorch/nightly/common.libsonnet
- dags/legacy_test/tests/pytorch/r2.3/common.libsonnet
Currently `accelerate test` fails in the setup phase:
```
[2024-04-16, 08:17:36 PDT] {logging_mixin.py:150} WARNING - + .local/bin/accelerate env
[2024-04-16, 08:17:43 PDT] {logging_mixin.py:150} WARNING - Traceback (most recent call last):
File "/home/ml-auto-solutions/.local/bin/accelerate", line 8, in <module>
sys.exit(main())
File "/home/ml-auto-solutions/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
args.func(args)
File "/home/ml-auto-solutions/.local/lib/python3.10/site-packages/accelerate/commands/env.py", line 67, in env_command
bash_location = subprocess.check_output(command, text=True, stderr=subprocess.STDOUT).strip()
File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
return run(*popenargs, stdout=PIPE, …
```
> Add HF accelerate to the PATH

- dags/examples/xpk_example_dag.py
Update example to ignore task group prefix in chained XPK tests to keep metric processing working as expected.
Upload to airflow and test.
Test: [link](https://screenshot.googleplex.com/9fPtR7vr2xWir4g)
> Ignore task group prefix in chained tests

- deployment/cloud_composer_template.tf
Add SA user role back that has been deleted in this [PR](https://github.com/GoogleCloudPlatform/ml-auto-solutions/pull/250/files), which causes permission missing in our tests ([link](https://screenshot.googleplex.com/AgNn5eRrEsam3kN))
Amin role is missing `iam.serviceAccounts.actAs` permission.
Manually add the permission, retrigger the test, and verified ([link](https://screenshot.googleplex.com/8Gujdqa4SskN6T9))
Manually add the permission, retrigger the test, and verified
> Add SA user role back

- dags/pytorch_xla/nightly.py
Per the nightly runs https://screenshot.googleplex.com/BN7rpqy45tAvfSE, `pt-nightly-accelerate-smoke-v2-8-1vm` failed to run due to `upstream_failed: 3`. The upstream `pt-nightly-accelerate-smoke-v4-8-1vm` failed due to lack of tpu v4 resource. We really need a way to run the HF accelerate test in order to catch regression regardless the TPU VM version (v2/v4). IOW, if we have TPU v2 resource, we should try to run the test on it even if we don't have TPU v4. This PR breaks the dependency of  HF accelerate v2 and v4 dependency so we always try to run the test.
**Instruction and/or command lines to reproduce your tests:** ...na
**List links for your tests (use go/shortn-gen for any internal link):** ...na
Before …
> Untie HF accelerate v2 and v4 dependency.

- dags/solutions_team/solutionsteam_jax_integration.py
v2-32 Jax tests are failing due to not being able to acquire capacity. Adding the reserved flags resolves that issue.
Ran the two relevant tests which are now passing: http://shortn/_zKfWWCHBri
> Adds the reserved flag for Jax pod tests

- dags/imagegen_devx/configs/project_bite_config.py
Update setup script to test nightly JAX against AxLearn HEAD
Failed at (probably this is what we want to test, catch, and fix)
```
[2024-04-30, 20:09:01 UTC] {logging_mixin.py:150} WARNING - + cd axlearn
[2024-04-30, 20:09:01 UTC] {logging_mixin.py:150} WARNING - + python -m axlearn.common.launch_trainer_main --module=text.gpt.c4_trainer --config=fuji_test --trainer_dir=gs://ml-auto-solutions/output/imagegen_devx/jax/jax_fuji_test-v4-8-2024-04-30-20-04-11/ --data_dir=gs://axlearn-public/tensorflow_datasets --jax_backend=tpu
[2024-04-30, 20:09:02 UTC] …
```
> Update setup script for Fuji test

- dags/multipod/maxtext_v5e_configs_perf.py
Add 128B int8 runs to maxtext v5e configs test
Ran MaxText 128B sweep on v5e-256 to find best config that fits into memory: http://shortn/_rEEZZ0FBzG
> Add 128B int8 runs to maxtext v5e configs test

- dags/multipod/maxtext_checkpointing.py
* Fix the script location for maxtext_checkpointing tests: https://github.com/google/maxtext/blob/main/end_to_end/test_checkpointing.sh
Tested the changes on local airflow server.
> Fix maxtext_checkpointing test script location

- dags/inference/configs/maxtext_inference_gce_config.py
- dags/inference/maxtext_inference.py
- Add llama2-70b-chat. MaxText checkpoint created by downloading and converting Meta's PyTorch checkpoint.
- Add v5p-8
- Parameterize a few more variables such as MAX_PREFILL_PREDICT_LENGTH, MAX_TARGET_LENGTH, and sleep time (to wait for JetStream server to start).
Ran in my local Composer environment. See dags here http://shortn/_gJ5bBfYLUi
> Add llama2-70b-chat with v5p-8

- dags/inference/configs/maxtext_inference_gce_config.py
- dags/inference/maxtext_inference.py
- Extract the commit hash of the maxtext and jetstream repos 
- Write additional metadata to BigQuery such as: `model_mode`, `maxtext_commit_hash`, `jetstream_commit_hash`, the `checkpoint` path, `scan_layers`, `dataset`, `max_prefill_predict_length`, `max_target_length`, `max_output_length`.
- Parameterize `model_mode`, `num_prompts`, `max_output_length`, `scan_layers`, `dataset` in the config.
Tested in my dev env
> Record commit hash of maxtext/jetstream, and parameterize additional info

- dags/inference/jetstream_inference_e2e.py
- Add JetStream E2E test for JetStream presubmit
- Test locally, the post_process failure is expected due to [not use prod composer](https://github.com/GoogleCloudPlatform/ml-auto-solutions/blob/master/xlml/utils/metric.py#L380-L383)
- http://127.0.0.1:8080/dags/jetstream_e2e_inference/grid?task_id=jetstream-e2e-inference-nightly-gemma-7b-per_device_batch_size-11-ici-fsdp1-ar-1-tensor1-v5litepod-8&tab=graph&dag_run_id=manual__2024-05-23T17%3A54%3A57.260364%2B00%3A00
> Add JetStream presubmit e2e test

- dags/multipod/maxtext_configs_aot_hybridsim.py
While running the Airflow tests for Hybridsim, noticed that `post_process` task checks for data in the result json. This [PR](https://github.com/GoogleCloudPlatform/ml-auto-solutions/pull/295) changed the name of the result file name that caused the `post_process` task to fail. This PR fixes the name of the result file.
Ran local Airflow server and verified the changes
> Change Hybridsim result file name

- dags/pytorch_xla/configs/pytorchxla_torchbench_config.py
- dags/pytorch_xla/pytorchxla2_torchbench.py
Torchbench daily run on torch-xla2.
I comment out tests on majority of GPU platforms to avoid competing resources with other runs.
Note: This PR depends on https://github.com/pytorch/xla/pull/7126/. Wait for that PR to merge before this one.
The dags should only impact torch_xla2
https://60bb71acc6784780b3bbdbae4ffa636f-dot-us-central1.composer.googleusercontent.com/dags/pytorchxla2-torchbench/grid
> Enable torchbench nightly tests on torch_xla2

- dags/multipod/maxtext_end_to_end.py
Extend Mixtral test timeout from 3 hours to 4 hours.
* current run on XL ML is very close to 3 hours, add some buffer period to test. 
N/A
> Extend Mixtral test timeout

- dags/solutions_team/solutionsteam_tf_nightly_supported.py
- dags/solutions_team/solutionsteam_tf_se_nightly_supported.py
+ remove tf keras api tests and only keep DLRM and Resnet tests
+ remove DLRM tests on v5p from se
http://shortn/_P5ISh6YZfj
http://shortn/_7GScBOJLxK
> Remove TF Keras API tests from tf nightly and tf se nightly and only keep Resnet and DLRM tests

- dags/multipod/maxtext_v5e_configs_perf.py
Adding GPT-3 175B model to nightly v5e perf tests. https://github.com/google/maxtext/pull/687 should be merged into maxtext before this PR is merged.
Ran in local composer env: https://screenshot.googleplex.com/BpfRWutGq2YCgsF
> Add gpt3 175B to nightly v5e perf tests

- dags/legacy_test/tests/pytorch/nightly/hf-diffusers.libsonnet
This is to fix failing Pytorch/XLA diffusers tests. One of the dependencies requires the version of pillow to be greater than 9.4.0 https://github.com/huggingface/datasets/pull/6883/files but we will have to wait for a new release of the dependency for a new version to be released. Temporarily fixing this by adding this line
> Update hf-diffusers.libsonnet to require Pillow >= 9.4.0

- deployment/clusters.tf
Add H100, V4, L4, V100 gke clusters from cloud-ml-benchmarking. I have already applied `terraform apply`.
Clusters are up without any issues [here](https://pantheon.corp.google.com/kubernetes/clusters/details/us-central1/benchmarking-gpu-uc1/nodes?e=13802955&mods=allow_workbench_image_override&project=cloud-ml-benchmarking).
> add H100, V4, L4, V100 gke clusters from cloud-ml-benchmarking

- dags/pytorch_xla/configs/pytorchxla_torchbench_config.py
Torch_xla2 GPU run need to set JAX_PLATFORMS=CUDA.
https://60bb71acc6784780b3bbdbae4ffa636f-dot-us-central1.composer.googleusercontent.com/dags/pytorchxla2-torchbench/grid?dag_run_id=manual__2024-06-18T19%3A58%3A37.252342%2B00%3A00&task_id=torchbench-background-matting-nvidia-h100-80gb.run_model.stream_logs&tab=logs
> fix torchxla2 GPU failure

- dags/inference/configs/jetstream_benchmark_serving_gce_config.py
- dags/inference/maxtext_inference.py
- dags/inference/maxtext_model_config_generator.py
Recent MaxText changes https://github.com/google/maxtext/pull/741 are causing failures. Removed `moe_matmul` to fix the failures.
> Remove moe_matmul parameter in JetStream+Maxtext benchmarks

- dags/legacy_test/tests/pytorch/nightly/llama2-model.libsonnet
This test relies on buckets that are no longer public. Granted read permissions to test SA and use `gsutil` to authenticate request.
> Fix permissions for PT/XLA llama tests

- xlml/utils/metric.py
Return empty string if tensorboard file is not found in GCS. Before, an `AirflowFailException` was raised if the tensorboard file was missing causing the `post_process` task to fail. If the `post_process` task fails, any dependent tests will also fail. The tensorboard file usually goes missing when running the model fails and no tensorboard file is generated. In this case, the `post_process` task should still succeed and upload the pass/fail test status to bigquery. 
Tested in local Composer env that post_process task still continues when tensorboard file in GCS is not found http://shortn/_3KUXYpZGGk
> Return empty string if gcs file location not found

- dags/legacy_test/tests/pytorch/nightly/llama2-model.libsonnet
Introduced in #352. Skipping tests since corresponding inference test is passing on nightly without this typo.
> Fix typo in PT/XLA llama2 test setup

- dags/composer_env.py
- dags/mantaray/mantaray.py
- scripts/upload-tests.sh
- xlml/utils/mantaray.py
- xlml/utils/metric.py
Enable running Mantaray jobs on XLML Airflow. 
Mantaray is a benchmarking library. The Mantaray DAG first downloads the Mantaray wheel and the Mantaray benchmarks from GCS, and then launches the benchmarks. 
Tested running Mantaray jobs e2e on the `cloud-ml-auto-solutions-dev` Composer Environment.
> Integrate Mantaray into XLML

- dags/solutions_team/configs/flax/solutionsteam_flax_latest_supported_config.py
fix flax tests by removing profiling from flax tests which is causing the grpc issue
The failing test `flax_resnet_imagenet-v5litepod-4` is now passing
> fix flax tests by disabling profiling from the flax tests

- .gitignore
- deployment/.terraform.lock.hcl
- deployment/artifact_registry.tf
- pyproject.toml
- Add basic configuration to package common library code in `xlml` in a Python package. This would allow us to create new Composer environments that share common code, but have their DAGs defined outside of this repository.
- Build with `pip wheel .`
- Add Terraform config for private Python Artifact Registry. 
- Documentation for pulling from a private Artifact Registry in Composer: https://cloud.google.com/composer/docs/how-to/using/installing-python-dependencies#install-ar-repo
I'm not planning to migrate the main prod/dev environments to use this package right now.
The terraform state was broken from a leftover lock (probably a canceled operation during #328) so there are some small inconsistencies. See next section.
<details>
```
Terraform used the selected providers to generate the …
```
> Package common library code in `xlml`

- dags/multipod/maxtext_v5e_configs_perf.py
Increase number of dependencies in v5e maxtext perf tests due to workload start timeouts.
DAG dependencies now look like this https://screenshot.googleplex.com/7TfW2uPwC3xo9Rn
N/A
> Increase number of dependencies in v5e maxtext perf tests

- dags/imagegen_devx/configs/jax_ss_config.py
- dags/imagegen_devx/jax_stable_stack_e2e.py
- dags/multipod/configs/common.py
- dags/multipod/maxtext_convergence.py
- dags/multipod/maxtext_end_to_end.py
- dags/multipod/maxtext_profiling.py
- dags/vm_resource.py
This change introduces JAX-Stable-Stack workload images for `maxtext` and `maxdiffusion`. Modified existing DAGs to incorporate these new images into our testing pipelines.
*Key Changes:*
New Images: Added JAX-SS images specifically optimized for maxtext and maxdiffusion workloads.
DAG Modifications: Updated relevant DAGs to consume these JAX-Stabke-Stack images during testing.
*Goals:*
Thorough Testing: Soak tests with JAX-Stabke-Stack images.
Potential Replacement: Evaluate the feasibility of replacing existing stable diffusion images with JAX-Stabke-Stack ML workload images if testing proves successful.
> Modified DAGs to consume jax-stable-stack docker image

- dags/multipod/maxtext_configs_aot.py
Add AoT tests for A3 GPUs.
Depends on this change in MaxText to support `EXECUTABLE` env var in 16vm.sh: https://github.com/google/maxtext/pull/826
http://shortn/_4tvul6cC2l
> Add AoT test for A3 GPU

- .github/CODEOWNERS
- dags/pytorch_xla/configs/pytorchxla_torchbench_config.py
- dags/pytorch_xla/pytorchxla2_torchbench.py
- dags/pytorch_xla/pytorchxla_torchbench.py
1. Use reserved resource for torchbench v5p;  
2. Use the new torch_xla wheel path based on https://github.com/pytorch/xla/pull/7883.
https://60bb71acc6784780b3bbdbae4ffa636f-dot-us-central1.composer.googleusercontent.com/dags/pytorchxla-torchbench/grid
> Use reserved v5p

- dags/imagegen_devx/jax_stable_stack_e2e.py
- dags/multipod/maxtext_configs_aot_hybridsim.py
- dags/multipod/maxtext_convergence.py
- dags/multipod/maxtext_end_to_end.py
- dags/multipod/maxtext_profiling.py
- dags/vm_resource.py
- Replacing `MAXTEXT_TPU_STABLE` docker image with jax stable stack maxtext docker image.
- Removing interim tests that were built to verify jax stable stack with workload in https://github.com/GoogleCloudPlatform/ml-auto-solutions/pull/353
> Replacing MAXTEXT_TPU_STABLE with jax stable stack maxtext docker image

- dags/legacy_test/tests/pytorch/nightly/common.libsonnet
It looks like we have stopped generating torch_xla-nightly wheel since August 28 and this is causing version mismatch in airflow tests.
Temporarily changing this link to point to 2.6 nightly before adding back the nightly wheel.
Tested on a dev airflow instance
> Update PyTorch/XLA nightly link.

- dags/multipod/maxtext_end_to_end.py
Adding tests for Mixtral-8x22B-Instruct-v0.1 via MaxText's end_to_end tests.
> end_to_end tests for mixtral-8x22b

- dags/multipod/maxtext_end_to_end.py
- dags/multipod/maxtext_gpu_end_to_end.py
Move GPU tests to a separate DAG. The GPU tests have been less stable than TPU, and being in the same DAG can cause real TPU failures to be overlooked.
* Deployed to test env: https://fc137785b6c943a4af82d0671bf0ebe5-dot-us-central1.composer.googleusercontent.com/home?tags=multipod_team
> Split GPU and TPU MaxText end_to_end tests

- dags/legacy_test/tests/pytorch/nightly/common.libsonnet
Current GPU tests are failing as they are using old torch version from python 3.8
> Update imageTag to nightly_3.10

- xlml/utils/mantaray.py
This allows users to pass in their personal gs bucket path when creating the Mantaray XLML job, during development. E.g. 
```
MANTARAY_GCS_BUCKET="gs://BUCKET_NAME" # your own gs bucket hosting mantaray code
TEST_MANTARAY_JOB="mantaray_job.py" # Your job file inside mantaray/xlml_jobs
with models.DAG(
dag_id=TEST_MANTARAY_JOB,
schedule=None,
tags=["mantaray"],
start_date=datetime.datetime(2024, 4, 22),
catchup=False,
) as dag:
run_workload = mantaray.run_workload(
workload_file_name=TEST_MANTARAY_JOB,
mantaray_gcs_bucket=MANTARAY_GCS_BUCKET,
)
run_workload
```
> make mantaray_gcs_bucket a param

- dags/examples/maxtext_sweep_gke_example_dag.py
- dags/imagegen_devx/jax_stable_stack_e2e.py
- dags/multipod/legacy.py
- dags/multipod/maxtext_checkpointing.py
- dags/multipod/maxtext_configs_aot.py
- dags/multipod/maxtext_convergence.py
- dags/multipod/maxtext_end_to_end.py
- dags/multipod/maxtext_profiling.py
- dags/multipod/maxtext_profiling_vertex_ai_tensorboard.py
- dags/multipod/maxtext_trillium_configs_perf.py
- dags/multipod/maxtext_v5e_configs_perf.py
- dags/vm_resource.py
- Refactored workloads on jax stable stack image Names to be in line with the standard 
- Refactored stable stack variable name for more clarity
> Refactoring Workload Stable Stack Images

- .github/CODEOWNERS
We need some redundancy for multipod reviewers, as a single point of failure can be a bottleneck.
This changes add @tonyjohnchen @raymondzouu  from the perf side ~and @RissyRan for the MOE side~, since these areas are the most frequent code changes.
N/A
> Add redundancy to multipod codeowners

- dags/legacy_test/tests/pytorch/r2.5/ci.libsonnet
- dags/legacy_test/tests/pytorch/r2.5/common.libsonnet
- dags/pytorch_xla/r2_5.py
> Add Trillium CI tests for 2.5 release

- dags/legacy_test/templates/tpus.libsonnet
- dags/legacy_test/tests/pytorch/nightly/ci.libsonnet
- dags/pytorch_xla/nightly.py
Enable v5p for PyTorch/XLA nightly CI.
https://60bb71acc6784780b3bbdbae4ffa636f-dot-us-central1.composer.googleusercontent.com/dags/pytorchxla-nightly/grid?dag_run_id=manual__2024-10-10T20%3A43%3A28.314559%2B00%3A00&task_id=pt-nightly-ci-func-v5p-8-1vm.provision.initialize.generate_tpu_name
> add v5p for PyTorch/XLA nightly CI

- dags/solutions_team/configs/vllm/vllm_benchmark_config.py
Previously the vLLM benchmarks were reading the HF_TOKEN from environment variables. This variable will get overwritten as part of regular updates. Instead, we are adding this variable to the Airflow variables which will be preserved.
> Fix vllm benchmark test failures

- dags/vm_resource.py
We recently released JAX Stable Stack version 0.4.35-rev1. And modified the M* models do build their images with the latest  JAX Stable Stack. 
This change is to update the M* versions to reflect that. 
ref: 
1. https://github.com/AI-Hypercomputer/maxtext/pull/978
2. https://github.com/AI-Hypercomputer/maxdiffusion/pull/126
Tested locally and verified that test passed on stable stack DAG
> Updated M* image versions to reflect jax_stable_stack=0.4.35-rev1

- deployment/modules/composer_env/main.tf
- xlml/utils/mantaray.py
Install MaxLibrary, a library that contains best model configs for MaxText models, during the set up for running Mantaray workloads on XLML
> Install maxlibrary when running mantaray tasks

- dags/imagegen_devx/configs/gke_config.py
- dags/imagegen_devx/jax_stable_stack_e2e.py
- dags/multipod/maxtext_configs_aot.py
- dags/multipod/maxtext_gpu_end_to_end.py
- dags/vm_resource.py
Context: 
A) We have created a new JAX Stable Stack image for GPUs with JAX version 0.4.35.
B) We have added support for creating new M* docker images in https://github.com/AI-Hypercomputer/maxtext/pull/981.
In this PR, we are: 
1. Updating the JAX Stable Stack DAG to run Maxtext on GCP GPUs with images that are built using JAX Stable Stack.
2. mportant: Changing the notion of "stable" for Maxtext GPU images — i.e., from "Stable" to "stable stack," which now points to images built using JAX Stable Stack.
> Adding tests for M* workload built on top of JAX Stable Stack for GPUs

- dags/legacy_test/tests/pytorch/nightly/common.libsonnet
- dags/legacy_test/tests/pytorch/r2.5.1/common.libsonnet
The existing code checks if unattended-upgr is active, then stops it. However, that has a race condition: unattended-upgr could have started running right after the check. As a result, our tasks still fail from time to time.
Here, we change the code to unconditionally stop unattended-upgr and disable the service, preventing it from running again. It will also forcefully remove the lock file.
~I can't start internal tests because the test composer instance can't schedule any jobs (http://shortn/_LSKNYM0gt7).
I'll monitor the status of airflow jobs after this PR is merged, and we can revert if it breaks things.~
Re-triggered the test: [test link](https://60bb71acc6784780b3bbdbae4ffa636f-dot-us-central1.composer.googleusercontent.com/dags/pytorchxla-nightly/grid?dag_run_id=manual__2024-10-29T …
> More reliably get rid of unattended-upgr

- dags/inference/configs/jetstream_benchmark_serving_gce_config.py
- dags/inference/maxtext_inference.py
These are related to failed workflows for MaxText + JetStream that stem from 
1. A dependence on a specific aqtp version that is no longer needed
2. Possible issues caused by too many parallel jobs.
Ran locally
> Removes aqtp version install, reduces parallel maxtext inf jobs

- dags/multipod/maxtext_gpu_end_to_end.py
- dags/quarantined_tests.py
- dags/test_owner.py
- xlml/apis/task.py
We would like to isolate flaky tests from mostly-green tests, so that we notice any further regressions. This PR creates a list of flaky tests, and puts them in a separate quarantined sub-group within each DAG. We do this for one initial DAG.
Checklist
X I have performed a self-review of my code.
X I have necessary comments in my code, particularly in hard-to-understand areas.
X I have run one-shot tests and provided workload links above if applicable.
X I have made or will make corresponding changes to the doc if needed.
> Quarantine flaky tests

- dags/imagegen_devx/jax_stable_stack_gpu_e2e.py
- dags/imagegen_devx/jax_stable_stack_tpu_e2e.py
- dags/imagegen_devx/maxdiffusion_e2e.py
- dags/multipod/maxtext_configs_aot.py
- dags/multipod/maxtext_configs_aot_hybridsim.py
- dags/multipod/maxtext_end_to_end.py
- dags/multipod/mxla_gpt3_6b_nightly_gke.py
- dags/multipod/mxla_maxtext_nightly_gke.py
- dags/quarantined_tests.py
- xlml/apis/task.py
Add quarantine TaskGroup for flaky tests in more multipod_team dags.
The PR includes a small refactor of maxtext_end_to_end and maxtext_configs_aot_hybridsim DAGs to facilitate quarantining, that should be functionally identical (in the former case improving readability / reuse).
> Quarantine more multipod_team tests

- dags/multipod/configs/jax_tests_gce_config.py
- dags/multipod/configs/jax_tests_gke_config.py
- dags/multipod/jax_functional_tests.py
Add tests for jax.distributed.initialize() function on the GKE platform for single slice and multislice using 2 slices.
Test logs: http://shortn/_kychJoMx2Q
> Add GKE tests for jax.distributed.initialize()

- dags/multipod/maxtext_end_to_end.py
- dags/sparsity_diffusion_devx/maxtext_moe_tpu_e2e.py
Fix test dependency issue in end_to_end tests
* noticed TPU tests are triggered before CPU ckpt conversion [here](https://screenshot.googleplex.com/6zLjTXSDkMUAbt4)
* reverse the order back
Upload to airflow and manually tested
test - [link](https://screenshot.googleplex.com/3Faawc4bERsU2NK)
> Fix test dependency issue

- dags/solutions_team/solutionsteam_tf_nightly_supported.py
32 is too large of an embedding dim for v5p and led to segmentation fault. Use 16 instead.
> Oncall v5p-8 dlrm test fix

- dags/solutions_team/solutionsteam_tf_nightly_supported.py
> Use V2_ALPHA_TPUV5 as runtime for TF nightly tests

- dags/map_reproducibility/aotc_reproducibility.py
- dags/map_reproducibility/nemo_gpt3.py
Changes:
Clone from GoB repo instead of GitHub for getting recipes by using git_cookie_authdaemon and using https googlesource link to copy.
General cleanup/refactor
Ran the test, it successfully deployed the cluster.
**Instruction and/or command lines to reproduce your tests:**  trigger DAG
**List links for your tests (use go/shortn-gen for any internal link):** http://shortn/_iRgQ5rTdM8
> Add GoB repo cloning mechanism

- dags/sparsity_diffusion_devx/maxtext_moe_tpu_e2e.py
Update MoE test config:
* Update 8x22b test to the same cluster as 8x7b
* With more tests ([PR](https://github.com/AI-Hypercomputer/maxtext/pull/1069)), add extra 30 min to the timeout.
Test on v4 cluster
* Test 8x22b - [link](https://pantheon.corp.google.com/kubernetes/service/us-central2/v4-128-bodaborg-us-central2-b/default/ranran-nightly-mixtral-8x22b-v4-3/logs?e=13803378&mods=allow_workbench_image_override&project=cloud-tpu-multipod-dev)
* Test 8x7b - [link](https://pantheon.corp.google.com/kubernetes/service/us-central2/v4-128-bodaborg-us-central2-b/default/ranran-nightly-mi …
> Update MoE test config

- .github/requirements.txt
- dags/mlcompass/maxtext_gke.py
- xlml/apis/task.py
Add MLCompass MaxText GKE runner for deploying and executing MaxText models, and add a `skip_prost_process` parameter to the xlml/apis/task to allow workflows bypass post-processing tasks.
```
blaze build -c opt third_party/mlcompass/executors/runners:tf_runner
blaze-bin/third_party/mlcompass/executors/runners/tf_runner \
--config_path=xlml/xlml_dev.pbtxt \
--benchmark_ids=1 \
--xlml_environment_name=orti-test \
--xlml_dag_name=mlcompass_maxtext_gke \
--xlml_build_docker_image=true \
--alsologtostderr
```
https://a2ca3cdf681d42a3aceb01b7d66a6681-dot-us-central1.composer.googleuser …
> Create mlcompass_maxtext_gke dag

- dags/legacy_test/tests/pytorch/nightly/common.libsonnet
- dags/pytorch_xla/configs/pytorchxla_torchbench_config.py
Since libtpu is switching Python package registries, we need to include both registries during the transition. https://github.com/pytorch/xla/blob/master/README.md is already updated but we need to update these hardcoded commands here as well.
Verified things in a test composer instance:
```
bash scripts/upload-tests.sh gs://us-central1-piz-a9563b85-bucket/dags
```
> Update the tpu dependency installation command

- dags/multipod/jax_functional_tests.py
- dags/multipod/legacy.py
- dags/multipod/maxtext_configs_aot_hybridsim.py
- dags/multipod/maxtext_convergence.py
- dags/multipod/maxtext_end_to_end.py
- dags/multipod/maxtext_gpu_end_to_end.py
- dags/multipod/maxtext_v5e_configs_perf.py
- dags/multipod/mxla_maxtext_nightly.py
- dags/multipod/pytorch.py
- dags/sparsity_diffusion_devx/maxtext_moe_tpu_e2e.py
- dags/sparsity_diffusion_devx/project_bite_gpu_e2e.py
- dags/sparsity_diffusion_devx/project_bite_tpu_e2e.py
Add the mlscale_onduty tag to dags that are actively monitored by the ML@Scale onduty
Just a tag change. Did not run one-shot tests.
> Adding mlscale_onduty tag

- dags/sparsity_diffusion_devx/configs/project_bite_config.py
- dags/sparsity_diffusion_devx/project_bite_tpu_e2e.py
- dags/test_owner.py
Update test owner for Bite on TPU
Upload to airflow and test
See expected owner [there](https://screenshot.googleplex.com/5ydFMg3TUtJF2nd)
> Update TPU Bite project owner

- .github/CODEOWNERS
- .github/requirements.txt
- dags/map_reproducibility/aotc_reproducibility.py
- dags/map_reproducibility/nemo_gpt3.py
- dags/map_reproducibility/utils.py
> clone aotc and get metrics from gcs and set pythonpath

- dags/inference/maxtext_inference_offline_benchmark.py
- dags/test_owner.py
Adds offline MLPerf benchmarking to run Llama2-70B v6e-8. Requires the changes in [related MaxText PR](https://github.com/AI-Hypercomputer/maxtext/pull/1056) to be merged in order to work correctly. 
Ran e2e using the dev environment. Confirmed completion and correct uploading of metrics after the run. 
Running the `maxtext_inference_offline_benchmark` DAG in the dev environment. 
Test history in dev environment: http://shortn/_QYByqVphuT
> Offline MLPerf Benchmarking

- deployment/modules/composer_env/main.tf
- xlml/utils/xpk.py
Short term fix xpk dependency (please see more details in issues for long-term fix: b/381315769)
We don't need to add dependency at infra level, but just install it before triggering xpk workload, so removing the unnecessary dependencies at terraform template.
* remove unneeded `ruamel.yaml`
* add `dacite` dependency (I see it has manually added into the prof env, we should keep them consistent, otherwise it will be overwrite if we apply terraform template)
Upload and test
Test it in dev env: [link](https://screenshot.googleplex.com/4FjRhCDYMADt3CG)
Before submitting this PR, …
> Short term fix xpk dependency

- dags/legacy_test/tests/pytorch/r2.6/common.libsonnet
- dags/pytorch_xla/configs/pytorchxla_torchbench_config.py
Update PyTorch/XLA 2.6 release tests to use RC3 wheel instead of RC1.
> Update PyTorch/XLA 2.6 release tests to target RC3

- pipeline/auto-push.cloudbuild.yml
Follow up to https://github.com/GoogleCloudPlatform/ml-auto-solutions/pull/521. Change autopush cloud build GCS bucket to the new location.
> Fix autopush cloud build GCS bucket

- dags/common/vm_resource.py
Update v6e XPK cluster
- Cluster: bodaborg-v6e-256-dnd-yucmhab
- Project: tpu-prod-env-one-vm
- Zone: us-east5-b
Ran the `maxtext-trillium-configs-perf` dag in my test environment, modifying so only a few XPK jobs ran instead of the full dag
```
bucket=us-central1-mattdavidow-dev-53a5a345-bucket
bash scripts/upload-tests.sh gs://$bucket/dags
```
Screenshot: http://shortn/_rXWMeoHAyJ
Test dag run: http://shortn/_tvbw4nzuC5
> Update v6e cluster

- dags/multipod/maxtext_profiling.py
In Nov. 2024, tensorflow has moved the profile plugin to a separate module (http://shortn/_JAWuKDskvf). However, this change was not included in the stable tensorflow release 2.18.0 in Oct. 2024, causing the ```_pywrap_profile_plugin``` import error in [b/381786481](https://b.corp.google.com/issues/381786481). This can be fixed using tf-nightly. Since the latest profiler has caught up with this change, we should consider switching back to stable tensorflow when the above change is included in the release.
Tested on my composer environment and previous import error was resolved. 
http://screen/BTFyNkfBBbkN7nv
> Fix maxtext_profiling import error by using tf-nightly

- dags/multipod/maxtext_profiling.py
In https://github.com/AI-Hypercomputer/maxtext/pull/1156, test_profiler.py was moved to the end_to_end folder in maxtext. This PR updates the path to reflect that change.
Fixes: [b/388640587](https://buganizer.corp.google.com/issues/388640587)
Local tests run with success. Need to wait one extra day for the Maxtext docker image to catch up.
> Update test_profiler.py path in maxtext_profiling

- dags/common/quarantined_tests.py
- dags/sparsity_diffusion_devx/maxtext_moe_tpu_e2e.py
Context: estimate the fix of b/384580048 will take sometime to dive deep why gke workloads take longer time than gce platform (30min on gce vs. 2hours/24hours on gke). We definitely don't want to block tests by this. So extract the tests out using a dedicated ckpt first.
Upload and test
test [link](https://screenshot.googleplex.com/46z3TQJnG4ZuTHb)
> Update 8x22b tests

- dags/multipod/maxtext_v5e_configs_perf.py
Disabling the nightly scheduled runs of the pathways perf tests in order to lessen the number of failing tests running in the cluster.  Will re-enable these tests once they are working. http://b/389097544 http://b/372059783.
N/A
> Disable pathways perf test scheduled run

- dags/legacy_test/tests/pytorch/nightly/stable-diffusion-2.libsonnet
- dags/legacy_test/tests/pytorch/nightly/targets.jsonnet
- dags/legacy_test/tests/pytorch/r2.6/stable-diffusion-2.libsonnet
- dags/legacy_test/tests/pytorch/r2.6/targets.jsonnet
- dags/pytorch_xla/nightly.py
- dags/pytorch_xla/r2_6.py
This change fixes https://github.com/pytorch/xla/issues/8542. See the linked proposal.
I referenced https://github.com/AI-Hypercomputer/tpu-recipes/tree/main/training/trillium/Diffusion-2-PyTorch when creating this test.
Tested in staging: http://shortn/_3B0clNTUmy
> [PyTorch/XLA] Add Stable Diffusion 2 training tests

- dags/common/test_owner.py
- dags/multipod/maxtext_gpu_end_to_end.py
- xlml/utils/gke.py
There are two major changes:
1. Update the tests to scale up the A3 cluster and scale down the cluster before and after the tests run, to resolve the issue that the cluster gets automatically scaled down while it's not being used.
2. Replace the owner of the tests with Yuwei.
1. Run the following commands:
$ git clone -b yangyuwei-maxtext-gpu https://github.com/GoogleCloudPlatform/ml-a
uto-solutions.git
$ cd ml-auto-solutions/
$ bash scripts/upload-tests.sh  gs://us-central1-nina-dags-fe347643-bucket/dags
2. Manually trigger `maxtext_gpu_end_to_end` DAG on the UI: https://540cef12d3da42ce97b48a97401b6c83-dot-us-central1.composer.googleusercontent.com/home …
> Update XLML tests for MaxText on GPUs. 

- dags/sparsity_diffusion_devx/jax_stable_stack_gpu_e2e.py
- dags/sparsity_diffusion_devx/project_bite_gpu_e2e.py
https://github.com/GoogleCloudPlatform/ml-auto-solutions/pull/556 introduced logic to spin up and down the A3 cluster. Given this additional layer to run tests on A3, this PR removes redundant tests that are:
a) Absorbed by the tests in MaxText end-to-end GPU DAG (MaxText JSTs)
b) Currently not relevant given the presence of JSTs for future A3Mega and beyond generation (AxLearn)
Verified locally
> Fixit: Removing redundant tests

- xlml/apis/task.py
- xlml/utils/xpk.py
Directly clean up xpk workloads after runs:
* This helps 1) clean up finished workloads to avoid perf regression to new workloads; 2) unblock other workloads in queue after Airflow timeout
* set all-done condition, so no matter the status of previous tasks, the workload will be cleaned-up
* remove the workload link (it will disappear), so update it to logging link
* to fix b/369152200
Upload to airflow and test funcitonality
* Test log link works fine on TPU - [link](https://screenshot.googleplex.com/6thyH5cQARydPXm), [logs](https://cloudlogging.app.goo.gl/LhLqUR7EdrSfqcrXA)
* …
> Clean up xpk workloads after runs

- dags/solutions_team/solutionsteam_vllm_benchmarks.py
Recent vLLM tests failed, potentially due to timeouts exceeding one hour.  Richard suggests reducing the number of request_rates tested to decrease overall test time. We only need to test powers of 2 (1, 2, 4, 8, 16, 32) for request_rates.
**Instruction and/or command lines to reproduce your tests:** I tested it in my dev environment. 
**List links for your tests (use go/shortn-gen for any internal link):**  https://069305c1662446849f63d550fbf4868f-dot-us-central1.composer.googleusercontent.com/dags/solutionsteam_vllm_benchmark/grid?search=solutionsteam_vllm_benchmark&dag_run_id=manual__2025-01-16T20%3A54%3A52.258412%2B00%3A00
> Reduce the number of request_rates

- xlml/utils/tpu.py
If a PyTorch/XLA DAG does not specify a timeout, the create_queued_resource function assumes that the timeout is 0 seconds, which is too short. We increase it to 2 hours.
The direct motivation is that CI DAGs have been timing out as they hit the 1 hour buffer time.
Verified that created VMs (e.g. http://shortn/_iGiaLzNSQ3) have a 2+1=3 hour TTL.
> Increase the default run model timeout

- dags/legacy_test/tests/pytorch/nightly/ci.libsonnet
- dags/legacy_test/tests/pytorch/nightly/llama2-model.libsonnet
- dags/legacy_test/tests/pytorch/r2.6/ci.libsonnet
- dags/legacy_test/tests/pytorch/r2.6/common.libsonnet
- dags/legacy_test/tests/pytorch/r2.6/llama2-model.libsonnet
- dags/pytorch_xla/configs/pytorchxla_torchbench_config.py
- Swap some jsonnet variable mixin order to set the right TPU VM system image type
- Upgrade to rc8 wheel to pickup new libtpu version
- Increase CI timeout to 3 hours to avoid timeout errors
http://shortn/_J0d2B7WZ3I
> [PyTorch/XLA] fix all r2.6 tests

- dags/legacy_test/tests/pytorch/nightly/common.libsonnet
- dags/legacy_test/tests/pytorch/r2.6/common.libsonnet
Previously we stopped unattended-upgrades. But test runs indicated that unattended-upgrades still runs occasionally. Here we attempt to fix that by removing the binary altogether.
Tested: http://shortn/_Hr1JOwekCA
> [PyTorch] Remove unattended-upgrades

- dags/multipod/maxtext_checkpointing.py
Updated maxtext_checkpointing test to test both async and sync
Minor tweaks to calling maxtext e2e test. Ran the test locally with same config 
> Update maxtext checkpoitin test to add async

- dags/legacy_test/tests/pytorch/nightly/llama2-model.libsonnet
- dags/legacy_test/tests/pytorch/r2.6/llama2-model.libsonnet
- dags/pytorch_xla/nightly.py
- dags/pytorch_xla/r2_6.py
- xlml/apis/test_config.py
Specifically, two slices of v5p-8.
This is to ensure that both r2.6 and ptxla nightly continue to work in multi-slice (DCN networking involved) environments.
I noticed that we are not testing llama3 in nightly so I added that too, copying from our release tests.
http://shortn/_q9gzUMfboD
> Add a multi-slice llama training test

- dags/solutions_team/configs/vllm/vllm_benchmark_config.py
This PR migrates the vLLM:TPU XLML test from a Python-based setup to a Docker-based setup. The Docker image uses the latest (unpinned) dependencies, allowing for proactive identification of dependency-related regressions and automating the vLLM:TPU benchmarking process.
1. Manually run the commands on Cloud TPU VMs
2. Run XLML test in my dev environment
**Instruction and/or command lines to reproduce your tests:** Upload local changes to the dev Composer environment, and manually trigger the DAG 
**List links for your tests (use go/shortn-gen for any internal link):** https://069305c1662446849f63d550fbf4868f-dot-us-central1.composer.googleusercontent.com/dags/solutionsteam_vllm_benchmark/grid?search=solutionsteam_vllm_be …
>  Migrate vLLM:TPU XLML Test from Python Setup to Docker with Latest Dependencies

- xlml/utils/xpk.py
Pathways jobs delete all pods on failure so the current `wait_for_workload_completion` does not recognize completion correctly. The new completion logic should be better than the current "check all pods" logic to determine if a workload is complete but because other logic with GPU workloads and print logs depending on the pods is colocated, I made only minimally invasive changes.
Ran both the maxtext_v5e_config_perf and pathways_maxtext_v5e_config_perf DAGs and they are WAI.
> Pathways job completion fix

- dags/common/quarantined_tests.py
- dags/common/vm_resource.py
- dags/multipod/configs/gke_config.py
- dags/multipod/mxla_maxtext_nightly_gke.py
- Update MXLA perf test to run Llama3 8B
- Update v5p-8 cluster location
- Delete v4 tests in favor of tests on v5p and v6e
https://screenshot.googleplex.com/6xWrgnwpqYTeWxe
> Update mxla test to use llama3 8B and remove v4 tests

- dags/solutions_team/configs/tensorflow/solutionsteam_tf_nightly_supported_config.py
Fix oncall test `tf_dlrm_criteo-v5p-8` by running `sudo apt-get -y update` before installing packages. 
> Fix oncall test `tf_dlrm_criteo-v5p-8`

- dags/multipod/maxtext_checkpointing.py
Change in formatting of `run_model_cmds` variable in https://github.com/GoogleCloudPlatform/ml-auto-solutions/pull/118 is causing the command in `dags/multipod/maxtext_checkpointing.py` to be formatted in this way: `set -xue;b;a;s;h; ;e;n;d;;t;o;;e;n;d;/;t;e;s;t;;c;h;e;c;k;p;o;i;n;t;i;n;g;.;s;h; ;c;h;e;c;k;p;o;i;n;t;i;n;g;-;s;t;a;b;l;e;-;1;x;-;v;4;-;8;-;a;s;y;n;c;`. As a result, the command is not able to execute as expected.
Tested on local airflow.
> Fix command in maxtext_checkpointing

- dags/sparsity_diffusion_devx/jax_stable_stack_gpu_e2e.py
Currently, the tests for JStS on A3Plus GPUs only tests for 1 node. This PR adds another testcase for testing on a multinode conifguration. 
Once A3Ultra support is added, these testcases will be rolled over to the new GPU generation and more testcases will be added in upcoming PRs.
Verified tests passing in Airflow.
[Link to Image] (https://screenshot.googleplex.com/9aV3xcXgegbzZ5y)
> Added MultiNode Test for JStS on A3Plus GPUs

- dags/sparsity_diffusion_devx/maxtext_moe_gpu_e2e.py
This PR adds `mlscale_onduty` tag to `maxtext_moe_gpu_e2e` DAG. It also ungroups the tests in the DAG
https://shortn.corp.google.com/add.py
http://shortn/_mji0MjBro6
> Add `mlscale_onduty` tag and ungroup tests

- dags/common/vm_resource.py
Cleaning up old jax images that are not used in any DAGs. 
FIXES: b/399672992
Verified that these images are old via artifact registry and that they are not used anywhere in the repo.
MAXDIFFUSION_TPU_JAX_NIGHTLY: https://screenshot.googleplex.com/8aWxrWZfDW9T4Qr
MAXTEXT_GPU_JAX_NIGHTLY: https://screenshot.googleplex.com/6NbjrhoN4JyuyWh 
> Removed unused and old docker images

- dags/multipod/jax_functional_tests.py
- dags/multipod/legacy.py
- dags/multipod/maxtext_checkpointing.py
- dags/multipod/maxtext_configs_aot.py
- dags/multipod/maxtext_configs_aot_hybridsim.py
- dags/multipod/maxtext_convergence.py
- dags/multipod/maxtext_end_to_end.py
- dags/multipod/maxtext_gpu_end_to_end.py
- dags/multipod/maxtext_multi_tier_checkpointing.py
- dags/multipod/maxtext_profiling.py
- dags/multipod/maxtext_profiling_vertex_ai_tensorboard.py
- dags/multipod/maxtext_trillium_configs_perf.py
- dags/multipod/maxtext_v5e_configs_perf.py
- dags/multipod/mxla_collective_nightly.py
- dags/multipod/mxla_gpt3_6b_nightly_gke.py
- dags/multipod/mxla_maxtext_nightly_gke.py
- dags/sparsity_diffusion_devx/jax_stable_stack_gpu_e2e.py
- dags/sparsity_diffusion_devx/jax_stable_stack_tpu_e2e.py
- dags/sparsity_diffusion_devx/maxdiffusion_e2e.py
- dags/sparsity_diffusion_devx/maxtext_moe_gpu_e2e.py
- dags/sparsity_diffusion_devx/maxtext_moe_tpu_e2e.py
Deprecate `mlscale_onduty` tag, and add separate tags for devx and perfx - [ref](https://docs.google.com/spreadsheets/d/1Wqjjvi7PKLhULjd9w_apxx9Lyr1W0ZYGACthcTWt50U/edit?resourcekey=0-DeDJI_AxJMWyvH7HHb4D8Q&gid=0#gid=0)
* 21 DAGs in total
* devx as `mlscale_devx`
* perfx as `mlscale_perfx`
Manually review
> Add separate tags for devx and perfx

- dags/multipod/maxtext_profiling.py
- dags/multipod/maxtext_profiling_vertex_ai_tensorboard.py
* Disable the MaxText/Vertex TB integration test
* Reduce the scope of the MaxText profiling test
* Only check that the XPlane is saved to GCS instead of running assertions on the profile itself
The reason for this change is that the profiling work is not owned by us anymore. Note that we will likely come back and remove the Vertex DAG completely. But for now, we will just stop it from being scheduled.
Will rely on the next Airflow run since these tests are already failing and aren't urgently needed
> Reduce MaxText profiling tests

- .gitignore
- dags/map_reproducibility/internal_runs/a3mega_maxtext_benchmarking_dags.py
- dags/map_reproducibility/internal_runs/a3ultra_maxtext_benchmarking_dags.py
- dags/map_reproducibility/utils/aotc_workload.py
- dags/map_reproducibility/utils/common_utils.py
- dags/map_reproducibility/utils/constants.py
- dags/map_reproducibility/utils/internal_aotc_workload.py
Added a3u internal benchmarking run dags and utils. Recipes are stored in internal gob repo [here](https://jax3p-gpu-benchmarking-review.git.corp.google.com/c/internal-gpu-recipes/+/1040).
tested new_internal_a3ultra_llama3.1-8b_8gpus_bf16_maxtext run on test xlml env called: yujun-zou-test1
a3u successful run:
https://screenshot.googleplex.com/4Q8mjf2nXAuCs7C
a3plus successful run: 
https://screenshot.googleplex.com/9MFmEF7E9wquyKs
> Add internal benchmarking runs

- dags/common/vm_resource.py
Update v6e [cluster name](https://pantheon.corp.google.com/kubernetes/clusters/details/us-east5/bodaborg-v6e-256-dnd-yucmhab-new/details?project=tpu-prod-env-one-vm&e=13803378&mods=allow_workbench_image_override&invt=AbtB2w) due to capacity migration. b/406305961
Manually check
> Update v6e cluster name

- dags/legacy_test/tests/pytorch/nightly/common.libsonnet
- dags/pytorch_xla/configs/pytorchxla_torchbench_config.py
This was failing because the latest nightly wheel changed from 2.7.0.dev+cxx11 to 2.8.0.dev
http://shortn/_ohYF2S0owt
It still fails at the end but that will be fixed by https://github.com/pytorch-tpu/transformers/pull/71
> Fix pt-nightly-llama3-train-func-v5p-8-1vm.run_model

- dags/common/vm_resource.py
- dags/sparsity_diffusion_devx/jax_stable_stack_tpu_e2e.py
The MaxDiffusion docker images used in XLML tests were pointing to old repositories that haven't been updated since end of January. This means that the tests were not running on true nightly builds. This commit updates the docker images such that they point to the right nightly and stable stack maxdiffusion builds.
FIXES: b/407771770
Testing:
Verified that the repo being updated is the one which maxdiffusion does nightly builds to. 
https://screenshot.googleplex.com/366FCiBBhfscH8Z 
Stable Stack Build: https://screenshot.googleplex.com/BqN4Qcjc2kFrAXg
Nightly Build: https://screenshot.googleplex.com/7WiV9EBrtd8yBMG
> Updated MaxDiffusion Docker Images to Proper Nightly and Stable Stack Repositories

- dags/multipod/maxtext_gpu_end_to_end.py
The stable tests in maxtext_gpu_end_to_end DAG use an old image that is not updated, causing XLML tests to fail. Now that jax stable stack for gpu is released, switch to the stable stack image for tests. 
Also, removing the pinned tests since they do not use jax stable stack for tests. Moving forward, the DAG will only use JStS stable image and rely on the jax_stable_stack_gpu_e2e DAG for testing the JStS stable and nightly image.
FIXES: b/392001678
The jax stable stack image passing tests: https://screenshot.googleplex.com/7zWC78QEWKWh6r4
Current stable image used in tests not being updated: https://screenshot.googleplex.com/7N8KMYimKUTTjzS
> Updated stable tests to use jax stable stack image

- dags/framework3p/microbenchmarks_dag.py
Some tests are failing due to hitting the default 60 minute timeout. Relax them to 120 minutes.
> Relax some timeouts in framework_microbenchmark

- dags/map_reproducibility/utils/common_utils.py
- dags/map_reproducibility/utils/internal_aotc_workload.py
add kubectl delete and force delete
Old pods deletion code are not work as expected: https://screenshot.googleplex.com/7U3XpALRBM8WqvJ
So we changed to the new force deletion cmd to grantee the release of resources. 
Jobs or pods are not guaranteed to be deleted by the ttl setup as well. Details [here](https://docs.google.com/document/d/1hBMgXc44p69k2QLt2XALLTlsuyFcomJc8cpzs38zHwk/edit?tab=t.faaa4oeom6t2#bookmark=id.eqy7n8uvwci2).
The new deletion logic is:
helm uninstall -> wait 60s -> regular kubectl delete ->wait 30s-> kubectl force delete
1. manual test that helm uninstall normally takes 60s: [here](https://paste.googleplex.com/6285594009010176)
2. if helm uninstall works: https://screenshot.googleplex.com/7TZgcrJFSsFG6U9
3. if helm uninstall not work but kubectl works: …
> add kubectl delete

- dags/map_reproducibility/internal_runs/a3mega_maxtext_benchmarking_dags.py
- dags/map_reproducibility/internal_runs/a3ultra_maxtext_benchmarking_dags.py
- dags/map_reproducibility/internal_runs/backfill_dags.py
reduce num of retry to save benchmarking time. Originally is the default 3 retries. Now it is changed to 2 for small workloads and 1 to large workloads
https://screenshot.googleplex.com/AKS9NPs8Kc5CAfZ
> reduce retry

- dags/multipod/maxtext_v5e_configs_perf.py
The pathways_maxtext_v5e_configs_perf airflow test fails because JAX_PLATFORMS=proxy and JAX_BACKEND_TARGET=... environment vars are missing (Thanks to Luke for rootcausing and suggesting a fix)
Summary of the issue:
- The pathways configs were only being set up in the xpk sub-command and not on-device. ([this](https://github.com/AI-Hypercomputer/maxtext/pull/1326) PR)
- The on-device test on Airflow is not passing the use_pathways flag (THIS PR)
FIXES: b/372059783
Please describe how you tested this change, and include any instructions and/or
commands to reproduce.
- `python3 benchmarks/benchmark_runner.py on-device --base_output_directory={OUTPUT_PATH}  --libtpu_type=maxtext-docker --num_steps=15 --use_pathways=True`
Before submitting this PR, please make sure (put X in square …
> Fix pathways v5e perf test

- dags/solutions_team/solutionsteam_vllm_benchmarks.py
Shifting the vllm benchmark test schedule by 12 hours to avoid conflicting with other tests.
> Shift vllm benchmark schedule by 12 hours

- dags/common/model_configs.py
- dags/multipod/maxtext_trillium_configs_perf.py
add deepseek3 trillium config for benchmarking
- already added "deepseek_v3_ep16" in [MaxText](https://github.com/AI-Hypercomputer/maxtext/blob/58bcbb1efbb3abe6add3918cecc7714e7b00d9c6/benchmarks/maxtext_trillium_model_configs.py#L1589-L1627)
- now link it to XLML
Using "maxtext_trillium_configs_perf.py" as a template, I create a local dag for testing pretraining of deepseek (num_slice=2, jax nightly docker).
- Code: https://screenshot.googleplex.com/AckdDpKYFBYbNzg
- Pretraining is successful: https://screenshot.googleplex.com/7kfX38i3Zg79EkH
> add trillium config for deepseek3

- dags/common/vm_resource.py
- dags/framework3p/configs/microbenchmarks_config.py
- dags/framework3p/microbenchmarks_dag.py
Fix microbenchmarks XLML failures:
1. Fix "accelerator-microbenchmarks already exists" error by adding `rm accelerator-microbenchmarks` before git clone.
2. Use the 'microbenchmark-runner' docker container instead of maxtext for XPK runs. 
3. remove v5p-128 and only keep v5p-256 to avoid resource contention.
Ran dag on ml-auto-solutions-dev
> Update dags for microbenchmarks

- dags/map_reproducibility/a3ultra/llama_3_1_405b_maxtext.py
- dags/map_reproducibility/a3ultra/llama_3_1_405b_nemo.py
- dags/map_reproducibility/a3ultra/llama_3_1_70b_maxtext.py
- dags/map_reproducibility/a3ultra/llama_3_1_70b_nemo.py
- dags/map_reproducibility/a3ultra/mixtral_8_7b_nemo.py
- dags/map_reproducibility/tests/test_common_utils.py
- dags/map_reproducibility/utils/common_utils.py
This PR modify the regression test for the a3ultra pretraining recipes (gpu-recipes)[https://github.com/ai-hypercomputer/gpu-recipes/]. The changes to the recipes is a consolidation of helm charts agnostic to the framework to use (maxtext/nemo). 
- Added test cases for all the helper functions added.
- Tested on internal test composer instance
python -m unittest discover dags/map_reproducibility/tests -p "test_common_utils.py"
Some of the tests done:
- [Llama-3.1-70b Nemo](http://shortn/_GckCNOtMEO)
- [Llama-3.1-405b Maxtext](http://shortn/_088u1H7MMM)
> Updating a3ultra tests to match the new recipes 

- dags/sparsity_diffusion_devx/maxtext_moe_tpu_e2e.py
In this PR, I add a new DAG to test Llama4 checkpoint conversion (on a CPU machine) and logits (on a v6e-256 pod).  I only test Scout for now, but the logic is there for Maverick if we want to enable that later on.
The corresponding MaxText PR can be found [here](https://github.com/AI-Hypercomputer/maxtext/pull/1715)
> Add DAGs/E2E checkpoint and forward logit tests for Llama4

- deployment/modules/composer_env/main.tf
Upgrade `prod` image: "composer-2.10.1-airflow-2.10.2"  -> "**composer-2.13.1-airflow-2.10.5**"
Why: Current image is too old for #728: c++ dependency issue
- failed for `dev`, used to be same as prod with [composer-2.10.1-airflow-2.10.2](https://screenshot.googleplex.com/6jT2fDaa2T5Kqbd): 
https://screenshot.googleplex.com/ZhyKVQBFq8Brx2k
```
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/venvqpko7so_/lib/python3.11/site-packages/tensorboard_plugin_profile/convert/_pywrap_profiler_plugin.so)
```
- succeed for `shuningjin-test` (my test env), used to have [composer-2.12.0-airflow-2.10.2](https://screenshot.googleplex.com/4aXUwZPhTi7SdZd): https://screenshot.googleplex.com/BVqBpKodNrAqA65
Checked the upgrade on dev env and my test …
> upgrade image version for production environment

- dags/common/model_configs.py
- dags/common/vm_resource.py
- dags/multipod/configs/common.py
- dags/multipod/maxtext_trillium_configs_perf.py
- add `maxtext_tpu_recipes` docker image to test Trillium tpu recipes
- remove some models to reduce the number of tests
Ran 2 tpu-recipe models: http://screen/nHYs6JK8rmPfSJZ
> Add maxtext trillium tpu-recipes regression tests

- dags/common/vm_resource.py
- dags/sparsity_diffusion_devx/maxtext_moe_gpu_e2e.py
The GPU pinned image build in maxtext is broken and needs to be deprecated. Replacing the pinned image which uses an old version of jax with the candidate JAII + maxtext gpu image. 
Ran tests in local Airflow to see that maxtext_moe_gpu_e2e DAG is pulling the gpu candidate image successfully. 
> Removed pinned gpu image and replaced with candidate JAII image

- dags/framework3p/configs/microbenchmarks_config.py
Testing out fix for oncall nightly test that is failing at `gsutil cp` step due to `AttributeError: module 'google._upb._message' has no attribute 'MessageMapContainer'`.
> Update microbenchmarks_config.py with gcloud storage cp instead of gsutil cp

- dags/map_reproducibility/utils/common_utils.py
clean up dag to clean jobset. jobsets end with cml-mixtral-8x7b-bf168a3um0603-wrq-workload-0.  We need to remove -workload-0 for the cleanup cmd
https://screenshot.googleplex.com/6NPGH5fUkAkobwp
> clean up dag to clean jobset

- dags/common/model_configs.py
- dags/common/test_owner.py
- dags/common/vm_resource.py
- dags/multipod/maxtext_v5p_configs_perf.py
Added changes to run regression tests on models llama2-7b, llama2-70b, gpt3-175b for TPU V5P
Tests pass for all models except llama2-7b(stable stack) due to a bug, which has been logged and assigned to corresponding owner.
https://screenshot.googleplex.com/5gUDDoLm5GtGqKb
> add v5p config for llama2-7b, llama2-70b, gpt3-175b

- .github/CODEOWNERS
dags/orbax will be used to store orbax DAGs.
Add Orbax code owners to the CODEOWNERS file. Subsequent Orbax PRs will be submitted to this dags/orbax folder
N/A
> Add code owners for dags/orbax

- dags/examples/always_fail.py
- plugins/README.md
- plugins/on_failure_actions.py
An Airflow Listener class to handle DAG run failures.
This listener specifically triggers actions when a DAG run fails.
It checks for the 'on_failure_alert' tag on the failed DAG. If the tag is present,
it proceeds to create a GitHub issue with details about the failed DAG run
and its failed tasks. The issue is assigned to the owners of the failed tasks
**Example issue:**
Example issues which made by triggering 'maxtext_end_to_end.py' in cienet-cmcs 
https://github.com/CIeNET-International/ml-auto-solutions-2/issues
An new example DAG always_fail.py can easily test this plugin.
> Add on_failure_listener plugin and always_fail.py example DAG for testing

- dags/multipod/maxtext_checkpointing.py
- dags/multipod/maxtext_sft_trainer.py
Move DAGS: `maxtext_sft_trainer` and `maxtext_checkpointing` to v5p-8 cluster
Tested on local airflow server
> Move sft and checkpointing dags to v5p cluster

- .github/CODEOWNERS
Add more cienet reviewers to help review new DAGs from multiple subprojects
> Add Cienet github reviewers

- dags/examples/always_fail.py
- plugins/README.md
- plugins/allow_list.txt
- plugins/on_failure_actions.py
To decouple the development of DAGs and the plugin, we modified the logic of the alert plugin.
Read the allow list and block list in the plugin folder to trigger.
In addition, I have added the DAGs Alex mentioned into allow_list.txt.
Manual test
> Change the mechanism to trigger the alert plugin by DAG

- dags/tpu_observability/interruption_validation_dag.py
This change adds a new DAG, which automates the validation of TPU interruption events by verifying the consistency between Cloud Monitoring metrics and Cloud Logging logs.
The DAG does not need to create any new resources; it fetches existing resource data via APIs to validate the consistency of interruption events.
The DAG can be configured to validate different interruption reasons and different platforms (GKE, GCE).
- Dag Name: interruption_event_validation_dag
- Airflow test results: https://8ea616621be647bea7fd8d5e664abcb1-dot-us-east1.composer.googleusercontent.com/dags/interruption_event_validation_dag/grid
- GCP Composer name: `dennis-airflow-test` (under GCP project: `cloud-ml-auto-solutions`)
- GCP Composer version: `2.13.1`
- `INTERRUPTION_MAX_LOG_RESULTS`:
- The maximum number …
> Add a new DAG that tests consistency between metric events and log entries

- plugins/README.md
- plugins/config.json
- plugins/on_failure_actions.py
1. Add config.json to save all configuration of all plugins.
2. Add a toggle to determine the default behavior of the GitHub alert plugin. A issue would be created as the toggle is true even if the finished dag wasn't in the allow_list.txt 
Manual Test
> Add alert plugin default toggle mechanism

- dags/map_reproducibility/a3ultra/llama_3_1_405b_maxtext.py
- dags/map_reproducibility/a3ultra/llama_3_1_70b_maxtext.py
- dags/map_reproducibility/a3ultra/mixtral_8_7b_maxtext.py
- dags/map_reproducibility/a4/llama3_1_70b/maxtext.py
- dags/map_reproducibility/a4/llama_3_1_405b/maxtext.py
- dags/map_reproducibility/internal_runs/a3mega_maxtext_benchmarking_dags.py
- dags/map_reproducibility/internal_runs/a3mega_maxtext_inference_benchmarking_dags.py
- dags/map_reproducibility/internal_runs/a3ultra_maxtext_benchmarking_dags.py
- dags/map_reproducibility/internal_runs/a4_maxtext_benchmarking_dags.py
- dags/multipod/maxtext_profiling_vertex_ai_tensorboard.py
Adding the "maxtext" tag to MaxText training tasks for A3 Mega, A3 Ultra, and A4 series within the map_reproducibility folder.
> Add maxtext tag into DAGs under map_reproducibility folder

- dags/multipod/maxtext_end_to_end.py
Fix a small typo in the MaxText llama2-7b end_to_end tests. Seeing this error in the Airflow tests:
```
bash: end_tp_end/tpu/llama2/7b/test_llama2_7b.sh: No such file or directory
```
Will let these tests run after merging and confirm they are working now
> Fix typo in MaxText llama2-7b e2e test

- dags/sparsity_diffusion_devx/jax_ai_image_candidate_tpu_e2e.py
Currently the candidate JAII DAG should be manual trigger only, since we only want to run it to verify a newly created candidate image. However, right now it is running everyday causing the DAG to be red.
Also, we can set the image pulled to be latest instead of a specific day since this DAG will only be using the latest candidate image created.
> Update candidate jaii dag

- dags/dashboard/configs/export_config.py
To show more data on the XLML dashbaord, we need to extend the time frame of query statements.
> change the data retrieval time range from 30 to 60 days for xlml dashboard
